// Mutation check: each deliberate break of a migration must make verify-stages.cjs fail,
// and for the right reason (the failing line is printed).
// Fix batch C (AUD-06, 05, 04, 03, 08, 12): SQL mutants run verify-stages (fix C SQL test); TS mutants
// run verify-payments (moyasar.ts) and verify-refunds (refunds.ts, end to end with the mock).
const FIXC_MUTANTS = [
  ['C', 'a test order moves without the flag (AUD-06)',
    "    if not coalesce(p_allow_test, false) then\n      return jsonb_build_object('status', 'test_order');",
    "    if false then\n      return jsonb_build_object('status', 'test_order');", false],
  ['C', 'the test-order flag works for any actor (AUD-06)',
    "    if not private.fabric_store_actor_is_admin(p_actor_id) then\n      return jsonb_build_object('status', 'forbidden');\n    end if;\n  end if;",
    "    if false then\n      return jsonb_build_object('status', 'forbidden');\n    end if;\n  end if;", false],
  ['C', 'the dashboard trial on a test order is not logged (AUD-06)',
    "  if p_to in ('preparing', 'ready_for_pickup', 'shipped', 'delivered') and v_environment = 'test' then\n    insert",
    "  if false then\n    insert", false],
  ['C', 'cancelling while the payment page is open (AUD-05)', '    if v_open_until is not null then', '    if false then', false],
  ['C', 'a payable declined page does not block cancelling (AUD-05)',
    "      and a.status in ('created', 'initiated', 'authorized', 'failed')\n      and a.expires_at > clock_timestamp();",
    "      and a.status in ('created', 'initiated', 'authorized')\n      and a.expires_at > clock_timestamp();", false],
  ['C', 'a declined invoice gets a second invoice beside it (AUD-05)',
    "    and a.status = 'failed'\n    and a.checkout_url is not null", "    and a.status = 'none'\n    and a.checkout_url is not null", false],
  ['C', 'a declined invoice about to end is still handed out (AUD-05)',
    '    if v_failed.expires_at > clock_timestamp() + c_reuse_min then', '    if true then', false],
  ['C', 'an external refund is not detected (AUD-03)', '          v_external := v_refunded > v_ledger;', '          v_external := false;', false],
  ['C', 'our own refund in flight counts as external (AUD-03)',
    "          where r.attempt_id = v_attempt_id and r.status in ('pending', 'succeeded');\n          v_external",
    "          where r.attempt_id = v_attempt_id and r.status in ('succeeded');\n          v_external", false],
  ['C', "Moyasar's refunded amount is not kept (AUD-03)",
    '          set provider_refunded_halalas = greatest(coalesce(provider_refunded_halalas, 0), v_refunded)\n          where id = v_attempt_id;\n          select',
    '          set provider_refunded_halalas = provider_refunded_halalas\n          where id = v_attempt_id;\n          select', false],
  ['C', 'refund_begin trusts the actor id (AUD-12)',
    "  -- الدفعة C (AUD-12): الاسترداد للمدير الفعّال — تفرضه القاعدة نفسها، لا مسار الخادم وحده.\n  if not private.fabric_store_actor_is_admin(p_actor_id) then",
    "  -- الدفعة C (AUD-12): الاسترداد للمدير الفعّال — تفرضه القاعدة نفسها، لا مسار الخادم وحده.\n  if false then", false],
  ['C', 'refund_close_unconfirmed trusts the actor id (AUD-12)',
    "  -- الدفعة C (AUD-12): قرار مالي للمدير الفعّال — تفرضه القاعدة نفسها.\n  if not private.fabric_store_actor_is_admin(p_actor_id) then",
    "  -- الدفعة C (AUD-12): قرار مالي للمدير الفعّال — تفرضه القاعدة نفسها.\n  if false then", false],
  ['C', 'record_external trusts the actor id (AUD-03/12)',
    "'bad_request');\n  end if;\n  if not private.fabric_store_actor_is_admin(p_actor_id) then",
    "'bad_request');\n  end if;\n  if false then", false],
  ['C', 'record_external accepts any amount (AUD-03)',
    '  if p_provider_refunded - v_ledger <= 0 or p_amount_halalas <> p_provider_refunded - v_ledger then',
    '  if p_provider_refunded - v_ledger <= 0 then', false],
  ['C', 'an extra payment may be refunded in part (AUD-04)',
    "    if p_cancel or p_amount_halalas <> v_remaining then\n      return jsonb_build_object('status', 'extra_full_only'",
    "    if p_cancel then\n      return jsonb_build_object('status', 'extra_full_only'", false],
  ['C', "refunding an extra payment changes the order's payment status (AUD-04)",
    '  if not v_extra then\n    perform set_config', '  if true then\n    perform set_config', false],
  ['C', 'a new refund after a closed sent one needs no reference (AUD-08)',
    '  if v_support is null and exists (', '  if false and exists (', false],
  ['C', 'an extra payment is not alerted (AUD-04)',
    "    where a.status = 'paid' and a.id is distinct from o.paid_attempt_id\n      and coalesce(rt.refunded, 0) < a.amount_halalas",
    "    where false\n      and coalesce(rt.refunded, 0) < a.amount_halalas", false],
  ['C', 'a payment on a cancelled order is not alerted (AUD-04)',
    "    where o.fulfillment_status = 'cancelled' and o.payment_status in ('paid', 'partially_refunded')",
    '    where false', false],
  ['C', 'an unrecorded external refund is not alerted (AUD-03)',
    "    where a.status = 'paid' and a.provider_refunded_halalas > coalesce(rt.recorded, 0)", '    where false', false],
  ['C', 'the old set_fulfillment is kept beside the new one',
    'drop function if exists public.fabric_store_staff_set_fulfillment(uuid, text, uuid, text, text, text);', 'select 1;', false],
  ['C', 'the old refund_begin is kept beside the new one',
    'drop function if exists public.fabric_store_refund_begin(uuid, uuid, text, bigint, text, boolean, uuid);', 'select 1;', false],
  ['C', 'a browser role may record an external refund',
    'grant execute on function public.fabric_store_refund_record_external(uuid, uuid, uuid, text, bigint, text, text, bigint, uuid) to service_role;',
    'grant execute on function public.fabric_store_refund_record_external(uuid, uuid, uuid, text, bigint, text, text, bigint, uuid) to service_role, authenticated;', false],
  ['C', 'the external reference can be rewritten',
    '  if new.support_reference is distinct from old.support_reference\n     or new.external_reference is distinct from old.external_reference then',
    '  if new.support_reference is distinct from old.support_reference then', false],
  ['C', 'functions we did not read are replaced (no fingerprint check, fix C)', '  if not v_ok then', '  if false then', false],
  ['C', 'encoding self-check removed (fix C)',
    "  if position(chr(1575) || chr(1604) || chr(1591) || chr(1604) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING",
    "  if false then\n    raise exception 'FABRIC_STORE_ENCODING", false],

  ['ts:moyasar.ts', '(fix C) a test key is accepted on the production deployment',
    "  if (environment === 'test' && (env.VERCEL_ENV ?? '').trim() === 'production'", '  if (false'],
  ['ts:payments.ts', '(fix C) the closing-invoice answer is generic',
    "  invoice_closing: [409, 'صفحة الدفع السابقة تنتهي خلال لحظات — أعيدي الضغط على «ادفعي» بعد دقيقة'],\n", ''],
  ['ts8:refunds.ts', '(fix C) the extra payment is not passed to the database',
    '    ...(input.attemptId ? { p_attempt_id: input.attemptId } : {}),\n', ''],
  ['ts8:refunds.ts', "(fix C) Moyasar support's reference is not passed",
    '    ...(input.supportReference?.trim() ? { p_support_reference: input.supportReference.trim() } : {}),\n', ''],
  ['ts8:refunds.ts', "(fix C) recording trusts the typed amount instead of asking Moyasar",
    '    current = (await deps.moyasar.fetchPayment(input.paymentId)).refunded ?? 0\n  } catch {\n    return { ok: false, httpStatus: 503, code: \'unavailable\', error: \'تعذّر سؤال ميسر عن الدفعة الآن — أعيدي المحاولة\' }\n  }\n  const { data, error } = await deps.rpc(\'fabric_store_refund_record_external\'',
    '    current = input.amountHalalas\n  } catch {\n    return { ok: false, httpStatus: 503, code: \'unavailable\', error: \'تعذّر سؤال ميسر عن الدفعة الآن — أعيدي المحاولة\' }\n  }\n  const { data, error } = await deps.rpc(\'fabric_store_refund_record_external\''],
]

// Fix batch D (AUD-14, AUD-10, AUD-09, AUD-07, AUD-13): SQL mutants run verify-stages (fix D SQL test + local
// checks); 'tsD:<path under src>' mutants break a COPY of src/ and run verify-privacy-ts.
const FIXD_MUTANTS = [
  ['D', 'visitors still read the whole fabrics table (AUD-14)', 'revoke select on table public.fabrics from anon;', 'select 1;', false],
  ['D', 'a cost column is granted to visitors (AUD-14)', 'grant select (\n  id,', 'grant select (\n  cost_per_meter, id,', false],
  ['D', 'the column drift check is gone (AUD-14)', '  if exists (\n    select 1 from unnest(array[', '  if false and exists (\n    select 1 from unnest(array[', false],
  ['D', 'an unpaid order\'s address may go at once (AUD-10)',
    "or (v_payment_status = 'pending' and v_payment_due_at < now() - interval '90 days')) then",
    "or (v_payment_status = 'pending' and v_payment_due_at < now())) then", false],
  ['D', 'the purge ignores the retention (AUD-10)', 'o.delivered_at < clock_timestamp() - p_retention', 'o.delivered_at < clock_timestamp()', false],
  ['D', 'the purge erases the city too (AUD-10)', '  set recipient_name = null, recipient_phone = null,', '  set city = null, recipient_name = null, recipient_phone = null,', false],
  ['D', 'a browser role may run the purge (AUD-10)',
    'grant execute on function public.fabric_store_purge_addresses(integer, interval) to service_role;',
    'grant execute on function public.fabric_store_purge_addresses(integer, interval) to service_role, authenticated;', false],
  ['D', 'paid attempts reconciled only 30 days (AUD-09)', "and o.paid_at > now() - interval '120 days'", "and o.paid_at > now() - interval '30 days'", false],
  ['D', 'after 30 days paid attempts are still asked daily (AUD-09)',
    "then interval '24 hours' else interval '30 days' end", "then interval '24 hours' else interval '24 hours' end", false],
  ['D', 'functions we did not read are replaced (no fingerprint check, fix D)',
    "    raise exception 'FABRIC_STORE_FIX_D_DRIFT: a deployed function", "    raise notice 'FABRIC_STORE_FIX_D_DRIFT: a deployed function", false],
  ['D', 'encoding self-check removed (fix D)',
    "  if position(chr(1575) || chr(1604) || chr(1591) || chr(1604) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING",
    "  if false then\n    raise exception 'FABRIC_STORE_ENCODING", false],

  ['tsD:lib/server/fabric-store/http.ts', '(fix D) the track token is the access token (AUD-07)',
    "update(`track:${checkoutKey}`, 'utf8')", "update(`access:${checkoutKey}`, 'utf8')"],
  ['tsD:lib/server/fabric-store/http.ts', '(fix D) any 64-hex token matches (AUD-07)',
    'return expected.length === given.length && timingSafeEqual(expected, given)', 'return expected.length === given.length'],
  ['tsD:lib/server/fabric-store/http.ts', '(fix D) the token travels in the query string (AUD-07)', '/fabrics/order/#n=', '/fabrics/order/?n='],
  ['tsD:lib/analytics-privacy.ts', '(fix D) analytics runs on order tracking (AUD-07)', ", '/fabrics/order/'] as const", '] as const'],
  ['tsD:lib/analytics-privacy.ts', '(fix D) page_location keeps the query (AUD-07)',
    "page_location: location.origin + location.pathname,", 'page_location: location.href,'],
  ['tsD:lib/server/alostaz-fabric-invoice.ts', '(fix D) a cut send stays «sending» (AUD-13)',
    "if (latestIncome.alostaz_sync_status === 'sending' && Number.isFinite(stuckSince)", 'if (false && Number.isFinite(stuckSince)'],
  ['tsD:lib/server/alostaz-fabric-invoice.ts', '(fix D) a send in progress is taken for cut (AUD-13)',
    'const STUCK_SENDING_MS = 10 * 60 * 1000', 'const STUCK_SENDING_MS = 60 * 1000'],
]

// Batch E (review REVIEW-CD.md): SQL via verify-stages; 'tsD:' (src copy) via verify-privacy-ts.
const FIXE_MUTANTS = [
  ['E', 'the purge accepts any retention again (R-CD-06)', "p_retention < interval '90 days' then", "p_retention < interval '0' then", false],
  ['E', 'a purge we did not read is replaced (no fingerprint check, batch E)',
    "    raise exception 'FABRIC_STORE_FIX_E_DRIFT", "    raise notice 'FABRIC_STORE_FIX_E_DRIFT", false],
  ['E', 'encoding self-check removed (batch E)',
    "  if position(chr(1575) || chr(1604) || chr(1605) || chr(1575) || chr(1604) || chr(1603) || chr(1577) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then", "  if false then", false],

  ['tsD:lib/analytics-privacy.ts', '(batch E) pushState/replaceState are not guarded (R-CD-07)',
    '          if (url !== undefined && url !== null) guard(String(url));\n', ''],
  ['tsD:lib/analytics-privacy.ts', '(batch E) the back button is not guarded (R-CD-07)',
    "      window.addEventListener('popstate', function () { guard(location.href); }, true);\n", ''],
  ['tsD:lib/analytics-privacy.ts', '(batch E) a sensitive page gets a page_view (R-CD-07)', "  if (excluded) return 'excluded'\n", ''],
  ['tsD:lib/analytics-privacy.ts', '(batch E) a sensitive first load sends a page_view (R-CD-07)',
    "send_page_view: !window['${GA_DISABLE_FLAG}']", 'send_page_view: true'],
  ['tsD:lib/fabric-store/store-alerts.ts', '(batch E) the seen key follows the reconciliation time',
    "`${alert.kind}|${alert.orderId ?? alert.detail}`", "`${alert.kind}|${alert.orderId ?? ''}|${alert.since ?? ''}`"],
  ['tsD:lib/server/fabric-store/payments.ts', '(batch E) events ignore the deadline (R-CD-05)',
    '    if (deadline !== undefined && Date.now() >= deadline) { outcomes.deferred = (outcomes.deferred ?? 0) + 1; continue }\n', ''],
  ['tsD:lib/server/fabric-store/payments.ts', '(batch E) reconciliation ignores the deadline (R-CD-05)',
    "    if (deadline !== undefined && Date.now() >= deadline) { add('deferred'); continue }\n", ''],
  ['tsD:lib/server/fabric-store/refunds.ts', '(batch E) refunds ignore the deadline (R-CD-05)',
    '    if (deadline !== undefined && Date.now() >= deadline) { counts.deferred = (counts.deferred ?? 0) + 1; continue }\n', ''],
  ['tsD:lib/server/fabric-store/confirm.ts', '(batch E) the outbox ignores the deadline (R-CD-05)',
    "    if (options.deadline !== undefined && Date.now() >= options.deadline) { count('deferred'); continue }\n", ''],
  ['tsD:lib/server/alostaz-fabric-invoice.ts', '(batch E) «review» announced though not written',
    "      return markError || markedCount !== 1 ? { kind: 'in_progress' } : { kind: 'review_required' }", "      return { kind: 'review_required' }"],
]

//   node scripts/db-local/mutate.cjs [2|3]
const { spawnSync } = require('node:child_process')
const path = require('node:path')

// [stage, name, find, replace, needsConcurrency, extraEdit?]
const MUTANTS = [
  // --- stage 4: the server entry point ---
  [4, 'browsers may create orders',
    'revoke all on function public.fabric_store_create_checkout(jsonb) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_create_checkout(jsonb) from public;', false],
  [4, 'browsers may read the quote snapshot',
    'revoke all on function public.fabric_store_quote_snapshot(uuid[], bytea) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_quote_snapshot(uuid[], bytea) from public;', false],
  // (Dropping service_role from the revoke alone is an EQUIVALENT mutant: there are no
  //  default privileges in schema private, live or here — checked 24 Sep 2026. The
  //  guarantee is "no role reaches the table", so the mutant grants it outright.)
  [4, 'the server may read or reset rate limits',
    'revoke all on table private.fabric_store_rate_limits from public, anon, authenticated, service_role;',
    'revoke all on table private.fabric_store_rate_limits from public, anon, authenticated, service_role;\ngrant select, delete on table private.fabric_store_rate_limits to service_role;', false],
  [4, 'the server may bump rate limits directly',
    '  from public, anon, authenticated, service_role;\n\n-- ---------------------------------------------------------------------------\n-- 2)',
    '  from public, anon, authenticated;\ngrant execute on function private.fabric_store_take_rate_limit(text, bytea, integer, interval) to service_role;\n\n-- ---------------------------------------------------------------------------\n-- 2)', false],
  [4, 'create runs with the caller search_path',
    "security definer\nset search_path = ''\nset lock_timeout = '800ms'", "security definer\nset lock_timeout = '800ms'", false],
  [4, 'a reused key with other inputs returns the old order',
    '    if v_existing.request_fingerprint = v_fingerprint and v_existing.access_token_hash = v_access_hash then',
    '    if true then', false],
  [4, 'a reused key with another token returns the old order',
    '    if v_existing.request_fingerprint = v_fingerprint and v_existing.access_token_hash = v_access_hash then',
    '    if v_existing.request_fingerprint = v_fingerprint then', false],
  [4, 'two submits of one key are not serialised',
    "  perform pg_advisory_xact_lock(hashtextextended('fabric_store_checkout:' || v_key::text, 0));",
    '  perform 1;', true],
  [4, 'rate limits never refuse', '  return v_hits <= p_limit;', '  return true;', false],
  [4, 'ten-minute sender limit raised', 'c_per_client_10m integer := 6;', 'c_per_client_10m integer := 600;', false],
  [4, 'daily sender limit raised', 'c_per_client_day integer := 30;', 'c_per_client_day integer := 3000;', false],
  [4, 'live orders per phone uncapped', 'c_live_orders_per_phone integer := 3;', 'c_live_orders_per_phone integer := 300;', false],
  [4, 'live orders in the store uncapped', 'c_live_orders_total integer := 50;', 'c_live_orders_total integer := 5000;', false],
  [4, 'a capped phone still cancels the order it replaces',
    "      raise exception using errcode = 'P0001', message = 'FABRIC_STORE_PHONE_LIMIT|limit';",
    "      return jsonb_build_object('status', 'phone_limit');", false],
  [4, 'refused attempts do not count (limit taken inside the undone block)',
    "  if not private.fabric_store_take_rate_limit('checkout_10m', v_client_hash, c_per_client_10m, interval '10 minutes')\n     or not private.fabric_store_take_rate_limit('checkout_day', v_client_hash, c_per_client_day, interval '1 day') then\n    return jsonb_build_object('status', 'rate_limited');\n  end if;\n\n  begin\n",
    "  begin\n  if not private.fabric_store_take_rate_limit('checkout_10m', v_client_hash, c_per_client_10m, interval '10 minutes')\n     or not private.fabric_store_take_rate_limit('checkout_day', v_client_hash, c_per_client_day, interval '1 day') then\n    return jsonb_build_object('status', 'rate_limited');\n  end if;\n", false],
  [4, 'the hold lasts 45 minutes', "c_hold interval := interval '30 minutes';", "c_hold interval := interval '45 minutes';", false],
  [4, 'the customer link lasts a day', "c_access interval := interval '90 days';", "c_access interval := interval '1 day';", false],
  [4, 'the line name comes from the request',
    "left(coalesce(nullif(btrim(v_listing.name), ''),", "left(coalesce(v_item ->> 'fabric_name', nullif(btrim(v_listing.name), ''),", false],
  [4, 'the stock unit comes from the request',
    'v_order_id, v_line, v_listing.id, v_listing.inventory_item_id, v_listing.inventory_color_id,',
    "v_order_id, v_line, v_listing.id, coalesce((v_item ->> 'inventory_item_id')::uuid, v_listing.inventory_item_id), v_listing.inventory_color_id,", false],
  [4, 'a card without stock behind it is accepted',
    '      if not found or v_listing.inventory_item_id is null then', '      if not found then', false],
  [4, 'order consistency checked only at commit',
    "                    public.fabric_store_order_addresses_consistency immediate;\n", "                    public.fabric_store_order_addresses_consistency deferred;\n", false],
  [4, 'an order with a payment attempt can be replaced',
    "            and attempt.status in ('created', 'initiated', 'authorized', 'paid')",
    "            and attempt.status in ('paid')", false],
  [4, 'a replaced order keeps its hold',
    "          perform private.fabric_store_release_order_reservations(v_old.id, 'استُبدل بطلب أحدث من نفس المتصفح');\n",
    '', false],
  [4, 'the quote ignores holds', "'reserved_cm', coalesce(hold.reserved_cm, 0)", "'reserved_cm', 0", false],
  [4, 'the quote is not rate limited', "'quote', p_client_hash, 60,", "'quote', p_client_hash, 6000,", false],
  [4, 'the quote takes any number of fabrics', 'cardinality(p_fabric_ids) > 40 then', 'cardinality(p_fabric_ids) > 4000 then', false],
  [4, 'encoding self-check removed (stage 4)',
    "  if position(chr(1602) || chr(1605) || chr(1575) || chr(1588) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then",
    '  if false then', false],

  // --- the third review: each missing guard must fail for its own reason ---
  [2, 'a paid order without a hold is not flagged',
    'if v_reservation_count <> v_item_count or v_bad_reservation then',
    'if v_bad_reservation then', false],
  [2, 'payment checks expiry at transaction start',
    'v_checked_at := clock_timestamp();',
    'v_checked_at := now();', true],
  [2, 'direct release re-locks the order after its hold',
    '    where o.id = new.order_id;\n    if v_order_payment',
    '    where o.id = new.order_id\n    for update;\n    if v_order_payment', true],
  // --- the reviewer's findings (revision 3): each fix must be caught if undone ---
  [3, 'the card in the line need not belong to this stock',
    '      if not v_listing_matches then',
    '      if false then', false],
  [2, 'a payment landing on a dead hold is not flagged',
    "    if new.payment_status = 'paid' and old.payment_status is distinct from 'paid' then",
    '    if false then', false],
  [2, 'the two-hour window is not on the row',
    '  constraint fabric_store_stock_reservations_window\n    check (expires_at <= created_at + interval \'2 hours\')',
    '  constraint fabric_store_stock_reservations_window\n    check (expires_at <= created_at + interval \'100 years\')', false],
  [2, 'an active hold may be extended by hand',
    '  if new.expires_at is distinct from old.expires_at then',
    '  if false then', false],

  // --- the reviewer's findings (revision 2): each fix must be caught if undone ---
  [2, 'audit sequence left with its default grants',
    "  execute format('revoke all on sequence %s from public, anon, authenticated, service_role', v_sequence);",
    '  null;', false],
  [2, 'fulfillment re-check only on the first step',
    "    if new.fulfillment_status in ('preparing', 'ready_for_pickup', 'shipped', 'delivered') then",
    "    if old.fulfillment_status = 'unfulfilled' and new.fulfillment_status = 'preparing' then", false],
  [2, "a paid order's hold may be released by hand",
    "  if new.status = 'released' and old.status = 'active' then",
    '  if false then', false],
  [3, 'anyone signed in may read the holds',
    "  if v_caller = 'anon'\n     or (v_caller = 'authenticated' and not private.can_manage_fabric_operations()) then",
    '  if false then', false],
  [3, "a paid order's hold is released anyway",
    "  if v_payment_status in ('paid', 'partially_refunded', 'refunded') then",
    '  if false then', false],
  [3, 'a price change since the quote is honoured anyway',
    "      if coalesce(round(v_listing_price * 100), -1)::bigint is distinct from v_line.price_per_meter_halalas",
    '      if false', false],
  [3, 'a hidden or deleted fabric is still sold',
    '      if not v_listing_visible then',
    '      if false then', false],
  [3, 'held stock can be deleted from the inventory screen',
    '  before delete on public.fabric_inventory_colors\n  for each row execute function private.fabric_store_block_reserved_stock_delete();',
    '  before delete on public.fabric_inventory_colors\n  for each row when (false) execute function private.fabric_store_block_reserved_stock_delete();', false],
  [3, 'shop guard ignores holds',
    "    if new.quantity > v_free then\n      raise exception using\n        errcode = 'P0001',\n        message = format(\n          'FABRIC_STOCK_RESERVED",
    "    if false then\n      raise exception using\n        errcode = 'P0001',\n        message = format(\n          'FABRIC_STOCK_RESERVED", false],
  [3, 'holds never expire',
    "      where r.inventory_color_id = p_color_id\n        and r.status = 'active'\n        and r.expires_at > now();",
    "      where r.inventory_color_id = p_color_id\n        and r.status = 'active';", false],
  [3, 'released holds still count',
    "      where r.inventory_color_id = p_color_id\n        and r.status = 'active'",
    "      where r.inventory_color_id = p_color_id\n        and r.status in ('active', 'released')", false],
  [3, 'holds on a fabric without colours ignored',
    "      where r.inventory_item_id = p_inventory_item_id\n        and r.inventory_color_id is null\n        and r.status = 'active'",
    "      where r.inventory_item_id = p_inventory_item_id\n        and r.inventory_color_id is null\n        and r.status = 'nothing'", false],
  [3, 'web hold ignores other holds',
    'if v_unit.required_cm > v_physical_cm - v_reserved_cm then', 'if v_unit.required_cm > v_physical_cm then', false],
  [3, 'web hold ignores metre→piece change',
    "         or (v_line.purchase_mode = 'meter' and v_physical_cm in (300, 350)) then", '         or false then', false],
  [3, 'web hold ignores a changed piece length',
    "      if (v_line.purchase_mode = 'piece' and v_line.piece_length_cm is distinct from v_physical_cm)", '      if false', false],
  [3, 'staff cannot read holds',
    'grant execute on function private.fabric_store_stock_hold(uuid, uuid) to authenticated, service_role;',
    'grant execute on function private.fabric_store_stock_hold(uuid, uuid) to service_role;', false],
  [3, 'sweep expires live holds',
    "    where r.status = 'active'\n      and r.expires_at <= now()", "    where r.status = 'active'", false],
  [3, 'hold window uncapped', "p_expires_at > now() + interval '2 hours'", 'false', false],
  [3, 'encoding self-check removed',
    "  if position(chr(1605) || chr(1581) || chr(1580) || chr(1608) || chr(1586) || chr(1577) in v_body) = 0\n     or position(chr(1575) || chr(1604) || chr(1603) || chr(1605) || chr(1610) || chr(1577) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then",
    '  if false then', false],
  [3, 'web hold takes no row lock',
    '      where color.id = v_unit.inventory_color_id\n        and color.inventory_item_id = v_unit.inventory_item_id\n      for update of color;',
    '      where color.id = v_unit.inventory_color_id\n        and color.inventory_item_id = v_unit.inventory_item_id;', true],
  [3, 'shop guard reads holds before taking the row lock',
    '  if new.color_id is not null then\n    select\n      color.current_quantity,',
    '  select hold.reserved_cm, hold.hold_until\n  into v_reserved_cm, v_hold_until\n  from private.fabric_store_stock_hold(new.inventory_item_id, new.color_id) hold;\n  perform pg_sleep(0.3);\n\n  if new.color_id is not null then\n    select\n      color.current_quantity,',
    true,
    ['  select hold.reserved_cm, hold.hold_until\n  into v_reserved_cm, v_hold_until\n  from private.fabric_store_stock_hold(new.inventory_item_id, new.color_id) hold;\n\n  if v_reserved_cm > 0 then',
     '  if v_reserved_cm > 0 then']],
  [3, 'web hold waits forever (no lock_timeout)', "set lock_timeout = '800ms'\nas $$", 'as $$', true],
  [2, 'encoding self-check removed (stage 2)',
    "  if position(chr(1575) || chr(1604) || chr(1591) || chr(1604) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then",
    '  if false then', false],
  [2, 'refund cap removed', 'if v_already + new.amount_halalas > v_attempt_amount then', 'if false then', true],
  [2, 'two open attempts allowed', 'create unique index fabric_store_payment_attempts_one_open_per_order', 'create index fabric_store_payment_attempts_one_open_per_order', true],
  [2, "browser roles keep default privileges",
    "revoke all on table public.fabric_store_orders from public, anon, authenticated, service_role;",
    "revoke all on table public.fabric_store_orders from service_role;", false],
  [2, "RLS off on refunds",
    "alter table public.fabric_store_refunds enable row level security;",
    "", false],
  [2, "service_role may rewrite snapshots",
    "grant select, insert on table public.fabric_store_order_items to service_role;",
    "grant select, insert, update, delete on table public.fabric_store_order_items to service_role;", false],
  [2, "sequence usable by anon",
    "revoke all on sequence public.fabric_store_order_number_seq from public, anon, authenticated, service_role;",
    "revoke all on sequence public.fabric_store_order_number_seq from service_role;", false],
  [2, "VAT truncated",
    "vat_basis_points + 5000) / 10000)",
    "vat_basis_points + 0) / 10000)", false],
  [2, "piece rounded twice",
    "(price_per_meter_halalas * (10000 - discount_basis_points) * piece_length_cm + 500000) / 1000000",
    "((price_per_meter_halalas * (10000 - discount_basis_points) + 5000) / 10000) * piece_length_cm / 100", false],
  [2, "meter line rounded down",
    "(unit_price_halalas * quantity_cm + 50) / 100",
    "(unit_price_halalas * quantity_cm) / 100", false],
  [2, "paid -> failed allowed",
    "or (old.payment_status = 'failed' and new.payment_status = 'paid')",
    "or (old.payment_status = 'failed' and new.payment_status = 'paid') or (old.payment_status = 'paid' and new.payment_status = 'failed')", false],
  [2, "staff changes payment",
    "if v_actor not in ('provider', 'system') then",
    "if v_actor not in ('provider', 'system', 'staff') then", false],
  [2, "actor optional",
    "and (v_actor is null or v_actor not in ('customer', 'staff', 'provider', 'system')) then",
    "and false then", false],
  [2, "prepare unpaid",
    "if new.payment_status not in ('paid', 'partially_refunded') then",
    "if false then", false],
  [2, "prepare under review",
    "      if new.needs_review then",
    "      if false then", false],
  [2, "paid attempt unverified",
    "if v_attempt_order is distinct from new.id or v_attempt_status is distinct from 'paid' then",
    "if false then", false],
  [2, "attempt amount unchecked",
    "if new.amount_halalas is distinct from v_total then",
    "if false then", false],
  [2, "items total unchecked",
    "if v_items_net <> v_order.items_net_halalas then",
    "if false then", false],
  [2, "snapshot trigger removed",
    "create trigger fabric_store_order_items_forbid_update\n  before update on public.fabric_store_order_items\n  for each row execute function private.fabric_store_forbid_update();",
    "", false],
  [2, "audit trigger removed",
    "create trigger fabric_store_orders_log_event\n  after insert or update on public.fabric_store_orders\n  for each row execute function private.fabric_store_log_order_event();",
    "", false],
  [2, "event payload mutable",
    "or new.payload is distinct from old.payload",
    "", false],
  [2, "reservation qty unmatched",
    "or v_item_consumption is distinct from new.quantity_cm then",
    "then", false],
  [2, "expired hold re-activates",
    "or (old.status in ('released', 'expired') and new.status = 'consumed')",
    "or (old.status in ('released', 'expired') and new.status in ('consumed', 'active'))", false],
  [2, "address wiped while open",
    "if not (v_fulfillment_status in ('delivered', 'cancelled') or v_payment_status = 'failed') then",
    "if false then", false],
  [2, "anonymised address editable",
    "if old.anonymized_at is not null then",
    "if false then", false],
  [2, "pickup stores address",
    "if v_delivery_method is distinct from 'shipping' then",
    "if false then", false],
  [2, "shipping without address",
    "if v_order.delivery_method = 'shipping' and not v_has_address then",
    "if false then", false],
  [2, "outbox dedupe removed",
    "constraint fabric_store_outbox_dedupe_key_key unique (dedupe_key),",
    "", false],
  [2, "duplicate events",
    "constraint fabric_store_payment_events_provider_event_key\n    unique (provider, environment, provider_event_id),",
    "", false],
  [2, "totals mutable",
    "or new.total_halalas is distinct from old.total_halalas",
    "", false],
  [2, "orders with attempts deletable",
    "order_id uuid not null references public.fabric_store_orders(id) on delete restrict,\n  provider text not null,",
    "order_id uuid not null references public.fabric_store_orders(id) on delete cascade,\n  provider text not null,", false],
  [2, "audit not writable by server",
    "grant select, insert on table public.fabric_store_order_events to service_role;",
    "grant select on table public.fabric_store_order_events to service_role;", false],
  [2, "provider payment id rewritable",
    "or (old.provider_payment_id is not null and new.provider_payment_id is distinct from old.provider_payment_id) then",
    "then", false],
  [2, "customer touches review flag",
    "if new.needs_review is distinct from old.needs_review and v_actor = 'customer' then",
    "if false then", false],
]

// --- stage 5: payments (SQL entry points + the TypeScript payment logic) ---
const STAGE5_MUTANTS = [
  [5, 'browsers may start payments',
    'revoke all on function public.fabric_store_begin_payment(bytea, text, bytea) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_begin_payment(bytea, text, bytea) from public;', false],
  [5, 'browsers may apply payments',
    'revoke all on function public.fabric_store_apply_payment(uuid, text, jsonb, uuid) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_apply_payment(uuid, text, jsonb, uuid) from public;', false],
  [5, 'apply runs with the caller search_path', "security definer\nset search_path = ''\nset lock_timeout = '2s'",
    "security definer\nset lock_timeout = '2s'", false],
  [5, 'pressing pay again opens a second invoice',
    "    if v_open.status in ('initiated', 'authorized') and v_open.expires_at > clock_timestamp()",
    '    if false and v_open.expires_at > clock_timestamp()', false],
  [5, 'a start in flight is not waited for',
    "    if v_open.status = 'created' and v_open.created_at > clock_timestamp() - interval '2 minutes' then",
    '    if false then', false],
  [5, 'the payment page outlives the hold', 'v_hold_until - c_hold_margin', "v_hold_until + interval '1 hour'", false],
  [5, 'no minimum payment window', 'v_expires < clock_timestamp() + c_min_window', 'v_expires < clock_timestamp()', false],
  [5, 'unlimited attempts per order', 'c_max_attempts integer := 5;', 'c_max_attempts integer := 50;', false],
  [5, 'payment starts not rate limited', "'payment_start', p_client_hash, 10,", "'payment_start', p_client_hash, 1000,", false],
  [5, 'status checks not rate limited', "'payment_status', p_client_hash, 120,", "'payment_status', p_client_hash, 12000,", false],
  [5, 'an http checkout url is attached', "or p_checkout_url is null or p_checkout_url !~ '^https://'", 'or p_checkout_url is null', false],
  [5, 'amount not compared', '       or v_amount is distinct from v_attempt.amount_halalas\n', '', false],
  [5, 'currency not compared', '       or v_currency <> v_attempt.currency\n', '', false],
  [5, 'a hint re-points an attempt with its own invoice',
    'where a.id = p_attempt_hint and a.provider_invoice_id is null;', 'where a.id = p_attempt_hint;', false],
  [5, 'authorisation counted as payment',
    "    elsif v_status in ('paid', 'captured') then", "    elsif v_status in ('paid', 'captured', 'authorized') then", false],
  [5, 'a late failure overwrites any attempt',
    "      if v_attempt.status in ('created', 'initiated', 'authorized') then", '      if true then', false],
  [5, 'a paid order queues no confirmation',
    "          insert into public.fabric_store_outbox (topic, dedupe_key, order_id, payload)\n          values ('confirm_order',",
    "          insert into public.fabric_store_outbox (topic, dedupe_key, order_id, payload)\n          values ('notify_customer',", false],
  [5, 'an overpayment is not flagged', "      if v_result = 'overpaid' then", '      if false then', false],
  [5, 'money on a cancelled order is not flagged', "          if v_order.fulfillment_status = 'cancelled' then", '          if false then', false],
  [5, 'a refund made outside the system is not flagged',
    "    elsif v_status in ('refunded', 'voided') and v_attempt.status = 'paid' then", '    elsif false then', false],
  [5, 'a repeated event is stored twice', '  on conflict (provider, environment, provider_event_id) do nothing\n', '', false],
  [5, 'failed events are retried forever', 'processing_attempts + 1 >= 10', 'processing_attempts + 1 >= 1000', false],
  [5, 'quarantined events are retried',
    "    where e.processing_status in ('received', 'failed')", "    where e.processing_status in ('received', 'failed', 'quarantined')", false],
  [5, 'fresh events are retried while their request still runs',
    "      and e.received_at < now() - interval '1 minute'\n", '', false],
  [5, 'a token sees another order’s attempt',
    'where a.id = p_attempt_id and a.order_id = v_order.id\n  for update;', 'where a.id = p_attempt_id\n  for update;', false],
  [5, 'every refresh asks Moyasar',
    "or v_attempt.last_verified_at < now() - interval '10 seconds')", 'or true)', false],
  [5, 'encoding self-check removed (stage 5)',
    "  if position(chr(1575) || chr(1604) || chr(1591) || chr(1604) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING",
    "  if false then\n    raise exception 'FABRIC_STORE_ENCODING", false],

  ['ts:payments.ts', 'the webhook secret is not checked',
    'if (!webhookSecretMatches(event.secret_token, config.webhookSecret)) {', 'if (false) {'],
  ['ts:payments.ts', 'the webhook body is trusted instead of re-fetched',
    'return ok(await processEvent(deps, recorded.event_id, paymentId))',
    'return ok((await applyVerifiedPayment(deps, recorded.event_id, event.data as never)).status)'],
  ['ts:payments.ts', 'card data is stored with the event',
    'created_at: event.created_at ?? null, data: redactPayment(data) }', 'created_at: event.created_at ?? null, data }'],
  ['ts:payments.ts', 'any checkout URL is accepted',
    'if (!isMoyasarCheckoutUrl(invoice.url) || invoice.amount', 'if (invoice.amount'],
  ['ts:payments.ts', 'the invoice amount is not checked',
    'invoice.amount !== begin.amount_halalas || ', ''],
  ['ts:payments.ts', 'a failed creation leaves the attempt open',
    "    await abandon(kind === 'rejected' ? 'create_rejected' : 'create_unknown', (error as Error).message)\n", ''],
  ['ts:payments.ts', 'an event from the other environment is processed',
    '  if (environment !== config.environment) {', '  if (false) {'],
  ['ts:payments.ts', 'no metadata recovery after a crash',
    "if (outcome.status === 'unknown' && payment.invoice_id) {", 'if (false) {'],
  ['ts:payments.ts', 'a transient Moyasar failure quarantines the event',
    "const final = error instanceof MoyasarError && (error.kind === 'not_found' || error.kind === 'rejected')",
    'const final = true'],
  ['ts:payments.ts', 'the return page never asks Moyasar',
    "if (view.status !== 'ok' || !view.verify_due", "if (true || !view.verify_due"],
  ['ts:moyasar.ts', 'live keys work without the launch flag',
    "if (environment === 'live' && (env.FABRIC_STORE_ALLOW_LIVE_PAYMENTS", "if (false && (env.FABRIC_STORE_ALLOW_LIVE_PAYMENTS"],
  ['ts:moyasar.ts', 'a foreign API base is accepted',
    "if (!local || env.NODE_ENV === 'production' || environment === 'live') {", 'if (false) {'],
  ['ts:moyasar.ts', 'Moyasar requests never time out',
    'const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS)', 'const timer = setTimeout(() => {}, REQUEST_TIMEOUT_MS)'],
  ['ts:moyasar.ts', 'the webhook secret comparison always matches',
    '  return timingSafeEqual(a, b)', '  return a.length === b.length'],
]

// --- stage 6: confirming the sale, the queue, the lock on online sales ---
const STAGE6_MUTANTS = [
  [6, 'browsers may confirm a sale',
    'revoke all on function public.fabric_store_confirm_order(uuid) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_confirm_order(uuid) from public;', false],
  [6, 'browsers may read the queue',
    'revoke all on function public.fabric_store_due_outbox(text[], integer, uuid) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_due_outbox(text[], integer, uuid) from public;', false],
  [6, 'confirm runs with the caller search_path',
    "security definer\nset search_path = ''\nset lock_timeout = '800ms'", "security definer\nset lock_timeout = '800ms'", false],
  [6, 'confirm waits behind a shop sale (no lock_timeout)',
    "set search_path = ''\nset lock_timeout = '800ms'\nas $$", "set search_path = ''\nas $$", true],
  [6, 'a test payment records a sale', "  if v_environment is distinct from 'live' then", '  if false then', false],
  [6, 'the hold is not consumed before the sale',
    "  update public.fabric_store_stock_reservations\n  set status = 'consumed',\n      end_reason = left('بيع إلكتروني ' || v_order.order_number, 200)\n  where order_id = p_order_id\n    and status <> 'consumed';\n",
    '', false],
  [6, 'other customers’ holds are ignored',
    "    where r.order_id <> p_order_id\n      and r.status = 'active'", "    where false\n      and r.status = 'active'", false],
  [6, 'the order’s own hold counts against it',
    "    where r.order_id <> p_order_id\n      and r.status = 'active'", "    where true\n      and r.status = 'active'", false],
  [6, 'fabric that is gone is sold anyway', '  if v_short is not null then', '  if false then', false],
  [6, 'a cancelled order is sold', "  if v_order.fulfillment_status = 'cancelled' then", '  if false then', false],
  [6, 'the sale amount leaves out VAT', 'round(v_order.total_halalas / 100.0, 2),', 'round(v_order.items_net_halalas / 100.0, 2),', false],
  [6, 'the online sale lands in the cash box', "    'network',\n    c_source,", "    'cash',\n    c_source,", false],
  [6, 'the online sale is editable on the shop screen', "    true,\n    case when v_shipping_gross > 0", "    false,\n    case when v_shipping_gross > 0", false],
  [6, 'the invoice number is left to the shop trigger',
    "  v_invoice := nextval('public.fabrics_invoice_number_seq');", '  v_invoice := null;', false],
  [6, 'no alostaz task is queued',
    "  values ('alostaz_invoice', 'alostaz_invoice:' || p_order_id::text, p_order_id,",
    "  values ('notify_customer', 'alostaz_invoice:' || p_order_id::text, p_order_id,", false],
  [6, 'the confirm task is never closed',
    "  where dedupe_key = 'confirm_order:' || p_order_id::text\n    and status not in ('done', 'dead');",
    "  where dedupe_key = 'confirm_order:' || p_order_id::text\n    and false;", false],
  [6, 'the review flag lifts despite another reason',
    "     and not exists (\n       select 1 from public.fabric_store_outbox t\n       where t.order_id = p_order_id and t.topic = 'notify_staff'\n     ) then",
    '     then', false],
  [6, 'the review flag never lifts', '     and v_order.review_reason = c_lapsed_reason', '     and false', false],
  [6, 'the online sale’s amount can change',
    '  if (to_jsonb(new) - c_mutable) is distinct from (to_jsonb(old) - c_mutable) then', '  if false then', false],
  [6, 'the online sale can be deleted',
    "  if tg_op = 'DELETE' then\n    raise exception", "  if false then\n    raise exception", false],
  [6, 'the alostaz sync cannot write the online sale',
    "'alostaz_customer_id', 'alostaz_invoice_id', 'alostaz_invoice_code', 'alostaz_sync_status',",
    "'alostaz_customer_id', 'alostaz_invoice_id', 'alostaz_invoice_code',", false],
  [6, 'the lock trigger is not created',
    'create trigger fabric_store_protect_online_sale\n  before update or delete on public.income',
    'create trigger fabric_store_protect_online_sale\n  before insert on public.income', false],
  [6, 'a retry is due at once', 'greatest(30, least(coalesce(p_retry_seconds, 300), 86400))', '0', false],
  [6, 'a task never gives up', "when p_outcome = 'dead' or t.attempts + 1 >= t.max_attempts then 'dead'", "when p_outcome = 'dead' then 'dead'", false],
  [6, 'the queue ignores the retry time', '      and t.run_after <= now()\n', '', false],
  [6, 'a finished task can be reopened', "  where t.id = p_task_id\n    and t.status not in ('done', 'dead')", '  where t.id = p_task_id', false],
  [6, 'encoding self-check removed (stage 6)',
    "  if position(chr(1575) || chr(1604) || chr(1591) || chr(1604) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING",
    "  if false then\n    raise exception 'FABRIC_STORE_ENCODING", false],

  ['ts6:confirm.ts', 'a lock timeout is not retried',
    '    if (!error.code || !LOCK_CODES.has(error.code) || attempt === attempts) break', '    break'],
  ['ts6:confirm.ts', 'a failed confirmation is not rescheduled',
    "        await finish(deps.rpc, task.id, 'retry', result.error ?? 'retry', retryDelaySeconds(task.attempts))\n", ''],
  ['ts6:confirm.ts', 'an unknown alostaz outcome is retried',
    "      return result.outcomeUnknown\n        ? { outcome: 'dead',", "      return result.outcomeUnknown\n        ? { outcome: 'retry',"],
  ['ts6:confirm.ts', 'a failed send is retried at once', 'Math.min(3600, 60 * 2 ** Math.max(0, attempts))', '0'],
  ['ts6:payments.ts', 'a verified payment does not record the sale',
    "if ((outcome.status === 'paid' || outcome.status === 'already_paid') && outcome.order_id && deps.onPaid) {",
    'if (false) {'],
  ['ts6:payments.ts', 'a failing after-payment step fails the payment',
    "    try {\n      await deps.onPaid(outcome.order_id)\n    } catch (error) {\n      console.error('fabric-store: after-payment step failed (the job will retry):', (error as Error).message)\n    }",
    '    await deps.onPaid(outcome.order_id)'],
  ['ts6:invoice-lines.ts', 'shipping is not its own line', '  if (shipping > 0) {', '  if (false) {'],
  ['ts6:invoice-lines.ts', 'totals are not compared',
    'if (!Number.isSafeInteger(total) || itemsTotal + shipping !== total || incomeHalalas !== total) {',
    'if (!Number.isSafeInteger(total)) {'],
]

// --- stage 7: staff actions on online orders ---
const STAGE7_MUTANTS = [
  [7, 'browsers may change an order',
    'revoke all on function public.fabric_store_staff_set_fulfillment(uuid, text, uuid, text, text, text) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_staff_set_fulfillment(uuid, text, uuid, text, text, text) from public;', false],
  ['7r', 'browsers may lift a review flag',
    'revoke all on function public.fabric_store_staff_resolve_review(uuid, uuid, text, jsonb) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_staff_resolve_review(uuid, uuid, text, jsonb) from public;', false],
  [7, 'a live payment is prepared before its sale',
    "     and v_environment = 'live' and v_order.income_id is null then", '     and false then', false],
  [7, 'a paid order is cancelled from the staff screen',
    "  if p_to = 'cancelled' and v_order.payment_status not in ('pending', 'failed') then", '  if false then', false],
  [7, 'shipped without a tracking number',
    "       or v_tracking is null or v_tracking !~ '^[A-Z0-9-]{3,60}$' then", '       then', false],
  [7, 'any text is a tracking number', "v_tracking !~ '^[A-Z0-9-]{3,60}$'", "v_tracking !~ '.'", false],
  [7, 'the staff id is not logged',
    "  perform set_config('fabric_store.actor_id', p_actor_id::text, true);\n\n  begin", '\n  begin', false],
  [7, 'a cancelled unpaid order keeps its hold',
    "    v_released := private.fabric_store_release_order_reservations(p_order_id, 'أُلغي الطلب من لوحة المتجر');",
    "    v_released := 0; -- أُلغي الطلب (يبقي الكلمة التي يفحصها الترميز)", false],
  ['7r', 'a review flag is lifted without a note',
    'if p_actor_id is null or v_note is null or char_length(v_note) not between 3 and 500 then\n    return jsonb_build_object(\'status\', \'note_required\');\n  end if;\n\n  select o.needs_review',
    "if p_actor_id is null then\n    return jsonb_build_object('status', 'note_required');\n  end if;\n\n  select o.needs_review", false],
  ['7r', 'staff alerts stay open after resolving',
    "    and topic = 'notify_staff'\n    and status <> 'done';", "    and false;", false],
  [7, 'shipping data allowed on pickup orders',
    '  add constraint fabric_store_orders_tracking_only_for_shipping\n    check (delivery_method',
    '  add constraint fabric_store_orders_tracking_only_for_shipping\n    check (true or delivery_method', false],
  ['7r', 'the old 3-argument resolve_review is kept (no snapshot check)',
    'drop function if exists public.fabric_store_staff_resolve_review(uuid, uuid, text);', '-- kept', false],
  ['7r', 'a stale review snapshot is accepted',
    '  if p_expected_review is distinct from v_snapshot then', '  if false then', false],
  ['7r', 'a new staff alert is left out of the snapshot',
    "where t.order_id = o.id and t.topic = 'notify_staff' and t.status <> 'done'))", "where false))", false],
  ['rf7r', 'resolving a shortage does not requeue the sale',
    "    where o.id = p_order_id and o.payment_status = 'paid' and a.environment = 'live'",
    "    where false and o.id = p_order_id and o.payment_status = 'paid' and a.environment = 'live'", false],
  ['rf7r', 'the requeue does not reopen a closed task',
    "      set status = 'pending', attempts = 0, run_after = now(), completed_at = null,",
    "      set", false],
  ['7r', 'encoding self-check removed (stage 7 review)',
    "     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING",
    "     and false then\n    raise exception 'FABRIC_STORE_ENCODING", false],
  [7, 'encoding self-check removed (stage 7)',
    "  if position(chr(1575) || chr(1604) || chr(1591) || chr(1604) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING",
    "  if false then\n    raise exception 'FABRIC_STORE_ENCODING", false],
]

// --- stage 8: refunds, cancel before the cut, restock, credit note ---
// SQL mutants run verify-stages.cjs (live-safe test + local refund test); 'ts8:<file>'
// mutants break a COPY of the TypeScript and run verify-refunds.cjs (mock Moyasar).
const STAGE8_MUTANTS = [
  [8, 'browsers may start a refund',
    'revoke all on function public.fabric_store_refund_begin(uuid, uuid, text, bigint, text, boolean, uuid) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_refund_begin(uuid, uuid, text, bigint, text, boolean, uuid) from public;', false],
  [8, 'a second refund while one is pending',
    "  if exists (select 1 from public.fabric_store_refunds r where r.order_id = p_order_id and r.status = 'pending') then\n    return jsonb_build_object('status', 'refund_in_progress');",
    "  if false then\n    return jsonb_build_object('status', 'refund_in_progress');", false],
  [8, 'cancel after the cut', "    if v_order.fulfillment_status <> 'unfulfilled' or v_order.cut_started_at is not null then",
    '    if false then', false],
  [8, '(review v2) cancel after a cut that was undone',
    "    if v_order.fulfillment_status <> 'unfulfilled' or v_order.cut_started_at is not null then",
    "    if v_order.fulfillment_status <> 'unfulfilled' then", false],
  [8, '(review v2) the cut can be erased',
    '  if old.cut_started_at is not null and new.cut_started_at is distinct from old.cut_started_at then', '  if false then', false],
  [8, '(review v2) the row allows cutting during a pending cancellation',
    "               where r.order_id = new.id and r.status = 'pending' and r.cancels_order) then", '               where false) then', false],
  [8, '(review v2) a late payment on a cancelled order cannot be refunded',
    "  if v_order.fulfillment_status = 'cancelled' then\n    -- (مراجعة 2)", "  if false then\n    -- (مراجعة 2)", false],
  [8, '(review v2) a stale claim token may mark the call',
    "  if p_claim_token is null or v_refund.claim_token is distinct from p_claim_token\n     or v_refund.locked_until",
    "  if false\n     or v_refund.locked_until", false],
  [8, '(review v2) a second call for the same refund',
    "  if v_refund.provider_called_at is not null then\n    return jsonb_build_object('status', 'already_called');",
    "  if false then\n    return jsonb_build_object('status', 'already_called');", false],
  [8, '(review v2) an old holder writes the result',
    "  if v_refund.claim_token is distinct from p_claim_token then\n    return jsonb_build_object('status', 'stale_claim');",
    "  if false then\n    return jsonb_build_object('status', 'stale_claim');", false],
  [8, '(review v2) an unconfirmed refund is flagged at once',
    "    if v_refund.provider_called_at is null or v_refund.provider_called_at > now() - interval '15 minutes' then", '    if false then', false],
  [8, 'a full refund before the cut without cancelling',
    "    if v_order.fulfillment_status = 'unfulfilled' and v_order.cut_started_at is null\n       and p_amount_halalas = v_remaining then", '    if false then', false],
  [8, 'a partial refund before the live sale exists',
    "    if v_attempt.environment = 'live' and v_order.income_id is null then\n      return jsonb_build_object('status', 'sale_pending');",
    "    if false then\n      return jsonb_build_object('status', 'sale_pending');", false],
  [8, 'a refund Moyasar does not show is recorded',
    '  if p_provider_refunded is null\n     or p_provider_refunded < v_refund.provider_refunded_before + v_refund.amount_halalas then\n    return',
    '  if false then\n    return', false],
  [8, 'no refund row in income', '  if found then\n    v_invoice := nextval', '  if false then\n    v_invoice := nextval', false],
  [8, 'the cancelled fabric does not go back', '      if v_order.income_id is not null then\n        for v_line in',
    '      if false then\n        for v_line in', false],
  [8, 'the cancellation does not cancel',
    "      set fulfillment_status = 'cancelled', cancel_reason = left(v_refund.reason, 300)",
    '      set cancel_reason = left(v_refund.reason, 300)', false],
  [8, 'restock above what was sold', '  if v_done + p_quantity_cm > v_item.stock_consumption_cm then', '  if false then', false],
  [8, 'a refund row in income can be edited',
    "     or old.category is null or old.category not in ('fabric_sale', 'fabric_store_refund') then",
    "     or old.category is null or old.category not in ('fabric_sale') then", false],
  [8, 'our own refunded webhook is quarantined', '          and v_refunded <= (select coalesce(sum(r.amount_halalas), 0)',
    '          and v_refunded < 0 and v_refunded <= (select coalesce(sum(r.amount_halalas), 0)', false],
  [8, 'a refund we never made is ignored',
    "                             where r.attempt_id = v_attempt_id and r.status in ('pending', 'succeeded')) then",
    "                             where r.attempt_id = v_attempt_id and r.status in ('pending', 'succeeded')) or true then", false],
  [8, 'cutting while a cancellation refund is pending',
    "                 where r.order_id = p_order_id and r.status = 'pending' and r.cancels_order) then",
    "                 where false) then", false],
  [8, 'the job takes a refund the route still holds',
    '      and (r.locked_until is null or r.locked_until < now())', '      and true', false],
  [8, 'the call is marked after the claim expired',
    "     or v_refund.locked_until is null or v_refund.locked_until < now() + interval '20 seconds' then", '     then', false],
  [8, 'a mismatch does not flag the order', "    if p_outcome = 'mismatch' then\n      v_reason", "    if false then\n      v_reason", false],
  [8, 'refund facts can be rewritten',
    '     or new.provider_refunded_before is distinct from old.provider_refunded_before\n', '', false],
  // (the same check exists in the correction; the message tail tells them apart)
  [8, 'encoding self-check removed (stage 8)',
    "     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING: this migration",
    "     and false then\n    raise exception 'FABRIC_STORE_ENCODING: this migration", false],
  [8, '(review v3) encoding self-check removed (stage 8 correction)',
    "     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING: refunded-first",
    "     and false then\n    raise exception 'FABRIC_STORE_ENCODING: refunded-first", false],
  ['ts8:refunds.ts', 'a lost answer is refunded again',
    '  if (refund.called && current >= target) {', '  if (false) {',
    false, ['  if (current !== refund.refundedBefore) {', '  if (false) {']],
  ['ts8:refunds.ts', 'the call is not recorded before it is made',
    "const { data: marked, error: markError } = await deps.rpc('fabric_store_refund_mark_called', {\n    p_refund_id: refund.refundId, p_claim_token: refund.claimToken })",
    "const { data: marked, error: markError } = { data: { status: 'ok' }, error: null }"],
  ['ts8:refunds.ts', 'a dashboard refund counts as ours', '  if (refund.called && current >= target) {', '  if (current >= target) {'],
  ['ts8:refunds.ts', 'a test key refunds a live payment', '  if (refund.environment !== deps.config.environment) {', '  if (false) {'],
  ['ts8:refunds.ts', 'an unknown outcome is a failure',
    "(error.kind === 'rejected' || error.kind === 'not_found')) {\n      await finish(deps.rpc, refund, 'failed', null, error.message)",
    "(true)) {\n      await finish(deps.rpc, refund, 'failed', null, error.message)"],
  ['ts8:refunds.ts', 'a refusal stays pending',
    "(error.kind === 'rejected' || error.kind === 'not_found')) {\n      await finish(deps.rpc, refund, 'failed', null, error.message)",
    "(false)) {\n      await finish(deps.rpc, refund, 'failed', null, error.message)"],
  ['ts8:moyasar.ts', 'the refund call sends no amount (refunds everything)', '{ amount: amountHalalas }', '{}'],
  ['ts8:refunds.ts', '(review v2) an unconfirmed call is never flagged',
    '  if (refund.called && current === refund.refundedBefore) {', '  if (false) {'],
  // --- the stage 8 correction (20260930135711): refunded-first + the 24h close ---
  [8, '(review v3) a payment first seen refunded is ignored',
    // (keeps the text the stage 9 precheck looks for, so the behaviour test must catch it)
    "    elsif v_status = 'refunded' and v_attempt.status <> 'paid' then", "    elsif v_status = 'refunded' and v_attempt.status <> 'paid' and false then", false],
  [8, '(review v3) an unconfirmed refund closes before 24 hours',
    "    if v_refund.provider_called_at > now() - interval '24 hours' then\n      return jsonb_build_object('status', 'too_early',",
    "    if false then\n      return jsonb_build_object('status', 'too_early',", false],
  [8, '(review v3) a refund Moyasar applied is closed as failed',
    '    if p_provider_refunded <> v_refund.provider_refunded_before then', '    if false then', false],
  [8, "(review v3) the manager's decision can be rewritten",
    '     or (old.review_reference is not null and (new.review_reference', '     or (false and (new.review_reference', false],
  [8, '(review v3) browsers may close a refund',
    'revoke all on function public.fabric_store_refund_close_unconfirmed(uuid, uuid, text, text, bigint) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_refund_close_unconfirmed(uuid, uuid, text, text, bigint) from public;', false],
  ['ts8:refunds.ts', '(review v3) the flag off still sends first calls',
    '  if (!allowNewCall) return', '  if (false) return'],
  ['ts8:refunds.ts', '(review v3) the close trusts the stored amount instead of asking Moyasar',
    '      current = (await deps.moyasar.fetchPayment(input.paymentId)).refunded ?? 0', '      current = null'],
]

// --- stage 9: reconciliation with Moyasar and staff alerts ---
// SQL mutants run verify-stages.cjs; 'rc9' mutants break the migration and run
// verify-reconcile.cjs (mock Moyasar); 'ts9:<file>' mutants break a COPY of the TypeScript.
const STAGE9_MUTANTS = [
  [9, 'browsers may read the alerts',
    'revoke all on function public.fabric_store_staff_alerts() from public, anon, authenticated;',
    'revoke all on function public.fabric_store_staff_alerts() from public;', false],
  [9, 'an open payment page is polled', '         and a.expires_at < now()\n', '', false],
  [9, 'an unpaid attempt is polled on every run',
    "         and (a.reconciled_at is null or a.reconciled_at < now() - interval '15 minutes'))",
    '         )', false],
  [9, 'a paid attempt is never re-checked', "        (a.status = 'paid'\n", "        (false and a.status = 'paid'\n", false],
  [9, 'the environment is ignored', '    where a.environment = p_environment\n', '    where true\n', false],
  [9, 'a dead task is not an alert', "    where t.status = 'dead'", '    where false', false],
  [9, 'an unconfirmed refund is not an alert',
    "    where r.status = 'pending' and r.provider_called_at < now() - interval '15 minutes'", '    where false', false],
  [9, 'encoding self-check removed (stage 9)',
    "     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING",
    "     and false then\n    raise exception 'FABRIC_STORE_ENCODING", false],
  ['rc9', 'a stuck sale is not an alert',
    "    where a.environment = 'live' and o.payment_status = 'paid' and o.income_id is null",
    "    where false and a.environment = 'live' and o.payment_status = 'paid' and o.income_id is null"],
  ['ts9:payments.ts', 'the job reads Moyasar but applies nothing',
    "      const outcomes = await applyInvoicePayments(deps, invoice, 'poll')", '      const outcomes: Record<string, number> = {}'],
  // (review v2) the reviewer's four notes + the 24h review alert
  [9, '(review v2) a live lease is handed out again', "      and (a.reconcile_claimed_at is null or a.reconcile_claimed_at < now() - interval '5 minutes')\n", '', false],
  [9, '(review v2) a stale claimant completes', '  where a.id = p_attempt_id and a.reconcile_claim_token = p_claim_token;', '  where a.id = p_attempt_id;', false],
  [9, '(review v2) claiming counts as a completed check',
    '    set reconcile_claimed_at = now(),\n', '    set reconcile_claimed_at = now(), reconciled_at = now(),\n', false],
  [9, '(review v2) an unconfirmed refund past 24h is not a review alert',
    "    where r.status = 'pending' and r.provider_called_at < now() - interval '24 hours'", '    where false', false],
  ['ts9:payments.ts', '(review v2) only the first ten payments are read',
    '  for (const payment of invoice.payments ?? []) {', '  for (const payment of (invoice.payments ?? []).slice(0, 10)) {'],
  ['ts9:payments.ts', 'the job asks with the wrong environment',
    "deps.rpc, 'fabric_store_due_reconciliation', { p_environment: deps.config.environment, p_limit: limit })",
    "deps.rpc, 'fabric_store_due_reconciliation', { p_environment: 'live', p_limit: limit })"],
]

// --- fix batch A (AUD-01 + the payroll RPCs): 'A' runs verify-finance-rls.cjs, 'P' runs verify-payroll-rpc.cjs ---
// Equivalent mutants left out on purpose (checked 1 Oct 2026):
//   • dropping `auth.uid() is not null and` — `u.id = auth.uid()` is already false for a null uid;
//   • dropping an UPDATE policy's `with check` — Postgres then applies its USING expression to the new row;
//   • `to authenticated` → `to public` — anon holds no table privilege at all, so no policy is reached.
const FIXA_MUTANTS = [
  ['A', 'anon keeps its table privileges', 'revoke all on table public.income, public.expenses from anon;\n', '\n'],
  ['A', 'signed-in users keep TRUNCATE', 'revoke truncate, references, trigger on table public.income, public.expenses from authenticated;\n', '\n'],
  ['A', 'anon keeps the invoice sequence', 'revoke all on sequence public.fabrics_invoice_number_seq from anon;\n', '\n'],
  ['A', 'anon keeps the recurring generator',
    'revoke execute on function public.generate_recurring_expenses(character varying, date) from public, anon;',
    'revoke execute on function public.generate_recurring_expenses(character varying, date) from public;'],
  ['A', 'the fabric manager reaches every branch',
    "w.worker_type = 'fabric_store_manager' and p_branch = 'fabrics')", "w.worker_type = 'fabric_store_manager')"],
  ['A', 'the accountant reaches the fabrics branch',
    "w.worker_type = 'accountant' and p_branch in ('tailoring', 'ready_designs'))", "w.worker_type = 'accountant')"],
  ['A', 'the general manager is let in',
    "        u.role = 'admin'\n        or (u.role = 'worker' and w.worker_type = 'fabric_store_manager'",
    "        u.role = 'admin' or w.worker_type = 'general_manager'\n        or (u.role = 'worker' and w.worker_type = 'fabric_store_manager'"],
  ['A', 'an inactive account is let in',
    "    where u.id = auth.uid()\n      and u.is_active = true\n      and (\n        u.role = 'admin'\n        or (u.role = 'worker' and w.worker_type = 'fabric_store_manager' and p_branch",
    "    where u.id = auth.uid()\n      and (\n        u.role = 'admin'\n        or (u.role = 'worker' and w.worker_type = 'fabric_store_manager' and p_branch"],
  ['A', 'income is readable by any signed-in user',
    'create policy income_staff_select on public.income for select to authenticated\n  using (private.can_access_finance_branch(branch));',
    'create policy income_staff_select on public.income for select to authenticated\n  using (true);'],
  ['A', 'any signed-in user may add income',
    'create policy income_staff_insert on public.income for insert to authenticated\n  with check (private.can_access_finance_branch(branch));',
    'create policy income_staff_insert on public.income for insert to authenticated\n  with check (auth.uid() is not null);'],
  ['A', 'an expense may move to a branch the actor does not hold',
    'create policy expenses_staff_update on public.expenses for update to authenticated\n  using (private.can_access_finance_branch(branch))\n  with check (private.can_access_finance_branch(branch));',
    'create policy expenses_staff_update on public.expenses for update to authenticated\n  using (private.can_access_finance_branch(branch))\n  with check (true);'],
  ['A', 'any signed-in user may delete expenses',
    'create policy expenses_staff_delete on public.expenses for delete to authenticated\n  using (private.can_access_finance_branch(branch));',
    'create policy expenses_staff_delete on public.expenses for delete to authenticated\n  using (auth.uid() is not null);'],
  ['A', 'a browser may rewrite the alostaz state of an online sale',
    "  if coalesce(current_setting('role', true), '') in ('anon', 'authenticated')", '  if false'],
  ['A', 'the alostaz state counts as staff-editable',
    "c_staff_mutable constant text[] := array['notes', 'fabric_images', 'fabric_inventory_tracked'];",
    "c_staff_mutable constant text[] := array['notes', 'fabric_images', 'fabric_inventory_tracked', 'alostaz_sync_status'];"],
  ['A', 'the server is locked out of the alostaz state too',
    "in ('anon', 'authenticated')", "in ('anon', 'authenticated', 'service_role')"],
  ['A', 'staff can no longer edit online-sale notes',
    "c_staff_mutable constant text[] := array['notes', 'fabric_images', 'fabric_inventory_tracked'];",
    "c_staff_mutable constant text[] := array['fabric_images', 'fabric_inventory_tracked'];"],
  ['A', 'unknown policies are replaced silently (no drift check)', '  if v_unknown is not null then', '  if false then'],
  ['A', 'a guard we did not read is replaced (no fingerprint check)',
    "  ) then\n    raise exception 'FABRIC_STORE_PROTECT_ONLINE_SALE_DRIFT", "  ) and false then\n    raise exception 'FABRIC_STORE_PROTECT_ONLINE_SALE_DRIFT"],
  ['A', 're-applying refuses its own guard', "        '8fd8694fded5ec1daaaf34e5b481fb15'  -- هذه الهجرة", "        'ffffffffffffffffffffffffffffffff'  -- هذه الهجرة"],
  ['A', 'encoding self-check removed (fix A)',
    "  if position(chr(1575) || chr(1604) || chr(1591) || chr(1604) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FINANCE_RLS_ENCODING",
    "  if false then\n    raise exception 'FINANCE_RLS_ENCODING"],

  ['P', 'a visitor may still call a wrapper',
    'revoke all on function public.unlock_worker_payroll_period(p_branch character varying, p_year integer, p_month integer) from public, anon;',
    'revoke all on function public.unlock_worker_payroll_period(p_branch character varying, p_year integer, p_month integer) from public;'],
  ['P', 'the fabric manager edits every branch',
    "w.worker_type = 'fabric_store_manager' and p_branch = 'fabrics')", "w.worker_type = 'fabric_store_manager')"],
  ['P', 'an inactive admin passes', "    where u.id = auth.uid()\n      and u.is_active = true\n", "    where u.id = auth.uid()\n"],
  ['P', 'one wrapper skips the role check',
    '  perform private.assert_payroll_branch_access(p_branch);\n  return public.register_worker_payroll_payment_unchecked',
    '  return public.register_worker_payroll_payment_unchecked'],
  ['P', 'an operation is checked against the wrong branch',
    '(select o.branch from public.worker_payroll_operations o where o.id = p_operation_id)', "'fabrics'"],
  ['P', 'a wrapper swaps two arguments',
    'p_reference => p_reference, p_note => p_note, p_payment_account => p_payment_account);\nend;\n$$;\nrevoke all on function public.register_worker_payroll_payment(',
    'p_reference => p_note, p_note => p_reference, p_payment_account => p_payment_account);\nend;\n$$;\nrevoke all on function public.register_worker_payroll_payment('],
  ['P', 'a wrapper changes a default',
    "p_note text DEFAULT NULL::text, p_payment_account character varying DEFAULT 'cash'::character varying)\nreturns jsonb\nlanguage plpgsql\nvolatile\nsecurity definer\nset search_path = ''\nas $$\nbegin\n  perform private.assert_payroll_branch_access(p_branch);\n  return public.register_worker_payroll_payment_unchecked",
    "p_note text DEFAULT NULL::text, p_payment_account character varying DEFAULT 'bank'::character varying)\nreturns jsonb\nlanguage plpgsql\nvolatile\nsecurity definer\nset search_path = ''\nas $$\nbegin\n  perform private.assert_payroll_branch_access(p_branch);\n  return public.register_worker_payroll_payment_unchecked"],
  ['P', 'an original stays callable by signed-in users',
    'revoke all on function public.unlock_worker_payroll_period_unchecked(p_branch character varying, p_year integer, p_month integer) from public, anon, authenticated, service_role;',
    'revoke all on function public.unlock_worker_payroll_period_unchecked(p_branch character varying, p_year integer, p_month integer) from public, anon;'],
  ['P', 'a helper stays open to the browser',
    'revoke all on function public.ensure_worker_payroll_month(character varying, text, text, integer, integer)\n  from public, anon, authenticated;', ''],
  ['P', 'a wrapper keeps the caller search_path',
    "returns jsonb\nlanguage plpgsql\nvolatile\nsecurity definer\nset search_path = ''\nas $$\nbegin\n  perform private.assert_payroll_branch_access(p_branch);\n  return public.create_worker_payroll_adjustment_request_unchecked",
    "returns jsonb\nlanguage plpgsql\nvolatile\nsecurity definer\nas $$\nbegin\n  perform private.assert_payroll_branch_access(p_branch);\n  return public.create_worker_payroll_adjustment_request_unchecked"],
  ['P', 'a body we did not read is wrapped (no drift check)', '    if v_fp is distinct from v_fn.fp then', '    if false then'],
  ['P', 're-applying renames again',
    "    if to_regprocedure(format('public.%s_unchecked(%s)', v_fn.name, v_fn.ident)) is null then\n      execute format('alter function",
    "    if true then\n      execute format('alter function"],
  ['P', 'encoding self-check removed (payroll)',
    "  if position(chr(1585) || chr(1608) || chr(1575) || chr(1578) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'PAYROLL_ENCODING",
    "  if false then\n    raise exception 'PAYROLL_ENCODING"],
]

// --- fix batch B (AUD-02): SQL mutants run verify-stages (--mutateB); 'ts:' ones run verify-payments ---
// Equivalent mutant left out on purpose: dropping service_role from the hold_clients revoke (no default
// privileges in schema private, live or here) — so the mutant grants it outright instead.
const FIXB_MUTANTS = [
  ['B', 'creating an order still holds the stock',
    "      raise exception using errcode = 'P0001', message = 'FABRIC_STORE_DRY_RUN|ok';\n", '', false],
  ['B', 'creating an order no longer validates price and stock',
    "      perform private.fabric_store_reserve_order(v_order_id, v_hold_until);\n      raise exception using errcode = 'P0001', message = 'FABRIC_STORE_DRY_RUN|ok';",
    "      raise exception using errcode = 'P0001', message = 'FABRIC_STORE_DRY_RUN|ok';", false],
  ['B', 'a six-line order is accepted', 'c_max_lines integer := 5;', 'c_max_lines integer := 6;', false],
  ['B', 'the hold at «ادفعي» lasts 45 minutes', "c_hold interval := interval '25 minutes';", "c_hold interval := interval '45 minutes';", false],
  ['B', 'six pieces per holder', 'c_cap_pieces_per_holder integer := 5;', 'c_cap_pieces_per_holder integer := 6;', false],
  ['B', '21 m per holder', 'c_cap_cm_per_holder bigint := 2000;', 'c_cap_cm_per_holder bigint := 2100;', false],
  ['B', '21 pieces on the store', 'c_cap_pieces_store integer := 20;', 'c_cap_pieces_store integer := 21;', false],
  ['B', '101 m on the store', 'c_cap_cm_store bigint := 10000;', 'c_cap_cm_store bigint := 10100;', false],
  ['B', 'the phone cap is not checked',
    '    if v_held.phone_pieces + v_need_pieces > c_cap_pieces_per_holder or v_held.phone_cm + v_need_cm > c_cap_cm_per_holder then',
    '    if false then', false],
  ['B', 'the sender cap is not checked',
    '    if v_held.client_pieces + v_need_pieces > c_cap_pieces_per_holder or v_held.client_cm + v_need_cm > c_cap_cm_per_holder then',
    '    if false then', false],
  ['B', 'the store cap is not checked',
    '    if v_held.store_pieces + v_need_pieces > c_cap_pieces_store or v_held.store_cm + v_need_cm > c_cap_cm_store then',
    '    if false then', false],
  ['B', 'two «ادفعي» are not serialised on the caps',
    "    perform pg_advisory_xact_lock(hashtextextended('fabric_store_hold_caps', 0));\n", '', true],
  ['B', 'the sender of «ادفعي» is not recorded',
    '    insert into private.fabric_store_hold_clients (order_id, client_hash) values (v_order.id, p_client_hash);\n', '', false],
  ['B', 'an order past its deadline is still held',
    '    if v_order.payment_due_at <= clock_timestamp() then', '    if false then', true],
  ['B', 'a refusal at «ادفعي» escapes as an error',
    "      if v_state = 'P0001' and position('|' in v_message) > 0 then\n        -- تغيّر السعر",
    "      if false then\n        -- تغيّر السعر", false],
  ['B', 'the server may read the senders',
    'revoke all on table private.fabric_store_hold_clients from public, anon, authenticated, service_role;',
    'revoke all on table private.fabric_store_hold_clients from public, anon, authenticated, service_role;\ngrant select on table private.fabric_store_hold_clients to service_role;', false],
  ['B', 'a begin_payment we did not read is replaced (no fingerprint check)',
    "  ) then\n    raise exception 'FABRIC_STORE_BEGIN_PAYMENT_DRIFT", "  ) and false then\n    raise exception 'FABRIC_STORE_BEGIN_PAYMENT_DRIFT", false],
  ['B', 'encoding self-check removed (fix B)',
    "  if position(chr(1575) || chr(1604) || chr(1591) || chr(1604) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING",
    "  if false then\n    raise exception 'FABRIC_STORE_ENCODING", false],

  ['ts:payments.ts', '(fix B) a hold limit gets a generic answer', "  if (begin.status === 'hold_limit') {", '  if (false) {'],
  ['ts:payments.ts', '(fix B) the database refusal message is dropped',
    "             error: begin.message || 'تغيّر شيء في طلبك منذ إنشائه — أعيدي إنشاء الطلب من السلة' }",
    "             error: 'تغيّر شيء في طلبك منذ إنشائه — أعيدي إنشاء الطلب من السلة' }"],
  ['ts:payments.ts', '(fix B) a shop sale holding the row is not recognised',
    "    if (error instanceof RpcFailure && error.code === '55P03') {", '    if (false) {'],
  ['ts:payments.ts', '(fix B) an expired order gets a generic answer',
    "  order_expired: [409, 'مضت مهلة الطلب قبل الدفع — أعيدي إنشاء الطلب من السلة'],\n", ''],
]

//   node scripts/db-local/mutate.cjs [2|3|4|5|6|7|8|9|ts|ts6|ts8|ts9|rf|rc9|A|P|B|C|D|E|tsD] [name substring]
// Stage 5/6 SQL mutants run verify-stages.cjs; 'ts:<file>' mutants break a COPY of
// src/lib/server/fabric-store/<file> and run verify-payments.cjs (end to end with the mock);
// 'ts6:<file>' mutants do the same with verify-confirm.cjs (stage 6).
const only = process.argv[2] || null
const nameFilter = process.argv[3] || null
let total = 0
let caught = 0
let inconclusive = 0
for (const [stage, name, find, replace, concurrency, extra] of [...MUTANTS, ...STAGE5_MUTANTS, ...STAGE6_MUTANTS, ...STAGE7_MUTANTS, ...STAGE8_MUTANTS, ...STAGE9_MUTANTS, ...FIXA_MUTANTS, ...FIXB_MUTANTS, ...FIXC_MUTANTS, ...FIXD_MUTANTS, ...FIXE_MUTANTS]) {
  if (only && !String(stage).startsWith(only)) continue
  if (nameFilter && !name.includes(nameFilter)) continue
  total += 1
  let args
  if (String(stage).startsWith('ts:')) {
    args = [path.join(__dirname, 'verify-payments.cjs'), '--mutate-ts', String(stage).slice(3), find, replace]
  } else if (stage === 'rf7r') {
    args = [path.join(__dirname, 'verify-review-fixes.cjs'), '--mutate7r', find, replace]
  } else if (stage === 'A') {
    args = [path.join(__dirname, 'verify-finance-rls.cjs'), '--mutateA', find, replace]
  } else if (stage === 'P') {
    args = [path.join(__dirname, 'verify-payroll-rpc.cjs'), '--mutateP', find, replace]
  } else if (stage === 'rc9') {
    args = [path.join(__dirname, 'verify-reconcile.cjs'), '--mutate9', find, replace]
  } else if (String(stage).startsWith('ts9:')) {
    args = [path.join(__dirname, 'verify-reconcile.cjs'), '--mutate-ts', String(stage).slice(4), find, replace]
  } else if (String(stage).startsWith('tsD:')) {
    args = [path.join(__dirname, 'verify-privacy-ts.cjs'), '--mutate-ts', String(stage).slice(4), find, replace]
  } else if (String(stage).startsWith('ts8:')) {
    args = [path.join(__dirname, 'verify-refunds.cjs'), '--mutate-ts', String(stage).slice(4), find, replace]
    if (extra) args.push('--mutate-ts', String(stage).slice(4), extra[0], extra[1])
  } else if (String(stage).startsWith('ts6:')) {
    args = [path.join(__dirname, 'verify-confirm.cjs'), '--mutate-ts', String(stage).slice(4), find, replace]
  } else {
    const flag = `--mutate${stage}`
    args = [path.join(__dirname, 'verify-stages.cjs'), flag, find, replace]
    if (extra) args.push(flag, extra[0], extra[1])
    if (!concurrency) args.push('--no-concurrency')
  }
  const run = spawnSync(process.execPath, args, { encoding: 'utf8', timeout: 600000, env: process.env })
  const out = `${run.stdout || ''}${run.stderr || ''}`
  if (run.status === 3) { console.log(`PATTERN MISSING: [${stage}] ${name}`); continue }
  if (run.status === 0) { console.log(`SURVIVED (bad): [${stage}] ${name}`); continue }
  // (المراجعة R-CD-04) لا يُحسب الفشل كشفاً إلا إن فشل فحص مسمّى (سطر ✘). انهيار الإعداد، أو مهلة،
  // أو منفذ مشغول، أو خطأ تشغيل بلا ✘ = غير حاسم: لا يثبت أن اختباراً كشف الطفرة.
  const failedCheck = out.match(/✘[^\n]*/)
  if (!failedCheck || run.status === null || run.error) {
    inconclusive += 1
    const reason = run.error ? run.error.message
      : run.status === null ? `killed (${run.signal})`
        : (out.trim().split('\n').pop() || '(no output)')
    console.log(`INCONCLUSIVE (rerun alone): [${stage}] ${name} → exit ${run.status}: ${reason.slice(0, 160)}`)
    continue
  }
  // تشغيل انهار في إعداده يطبع غالباً «run aborted» — ليس فحصاً سلوكياً
  if (/✘ run aborted|✘ setup:/.test(failedCheck[0])) {
    inconclusive += 1
    console.log(`INCONCLUSIVE (setup failed): [${stage}] ${name} → ${failedCheck[0].slice(0, 160)}`)
    continue
  }
  caught += 1
  console.log(`caught: [${stage}] ${name} → ${failedCheck[0].slice(0, 140)}`)
}
console.log(`mutants: ${total}, caught: ${caught}${inconclusive ? `, INCONCLUSIVE: ${inconclusive}` : ''}`)
process.exit(caught === total ? 0 : 1)
