// Mutation check: each deliberate break of a migration must make verify-stages.cjs fail,
// and for the right reason (the failing line is printed).
//   node scripts/db-local/mutate.cjs [2|3]
const { spawnSync } = require('node:child_process')
const path = require('node:path')

// [stage, name, find, replace, needsConcurrency, extraEdit?]
const MUTANTS = [
  // --- stage 4: the server entry point ---
  [4, 'browsers may create orders',
    'revoke all on function public.fabric_store_create_checkout(jsonb) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_create_checkout(jsonb) from public;', false],
  [4, 'browsers may read the quote snapshot',
    'revoke all on function public.fabric_store_quote_snapshot(uuid[], bytea) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_quote_snapshot(uuid[], bytea) from public;', false],
  // (Dropping service_role from the revoke alone is an EQUIVALENT mutant: there are no
  //  default privileges in schema private, live or here — checked 24 Sep 2026. The
  //  guarantee is "no role reaches the table", so the mutant grants it outright.)
  [4, 'the server may read or reset rate limits',
    'revoke all on table private.fabric_store_rate_limits from public, anon, authenticated, service_role;',
    'revoke all on table private.fabric_store_rate_limits from public, anon, authenticated, service_role;\ngrant select, delete on table private.fabric_store_rate_limits to service_role;', false],
  [4, 'the server may bump rate limits directly',
    '  from public, anon, authenticated, service_role;\n\n-- ---------------------------------------------------------------------------\n-- 2)',
    '  from public, anon, authenticated;\ngrant execute on function private.fabric_store_take_rate_limit(text, bytea, integer, interval) to service_role;\n\n-- ---------------------------------------------------------------------------\n-- 2)', false],
  [4, 'create runs with the caller search_path',
    "security definer\nset search_path = ''\nset lock_timeout = '800ms'", "security definer\nset lock_timeout = '800ms'", false],
  [4, 'a reused key with other inputs returns the old order',
    '    if v_existing.request_fingerprint = v_fingerprint and v_existing.access_token_hash = v_access_hash then',
    '    if true then', false],
  [4, 'a reused key with another token returns the old order',
    '    if v_existing.request_fingerprint = v_fingerprint and v_existing.access_token_hash = v_access_hash then',
    '    if v_existing.request_fingerprint = v_fingerprint then', false],
  [4, 'two submits of one key are not serialised',
    "  perform pg_advisory_xact_lock(hashtextextended('fabric_store_checkout:' || v_key::text, 0));",
    '  perform 1;', true],
  [4, 'rate limits never refuse', '  return v_hits <= p_limit;', '  return true;', false],
  [4, 'ten-minute sender limit raised', 'c_per_client_10m integer := 6;', 'c_per_client_10m integer := 600;', false],
  [4, 'daily sender limit raised', 'c_per_client_day integer := 30;', 'c_per_client_day integer := 3000;', false],
  [4, 'live orders per phone uncapped', 'c_live_orders_per_phone integer := 3;', 'c_live_orders_per_phone integer := 300;', false],
  [4, 'live orders in the store uncapped', 'c_live_orders_total integer := 50;', 'c_live_orders_total integer := 5000;', false],
  [4, 'a capped phone still cancels the order it replaces',
    "      raise exception using errcode = 'P0001', message = 'FABRIC_STORE_PHONE_LIMIT|limit';",
    "      return jsonb_build_object('status', 'phone_limit');", false],
  [4, 'refused attempts do not count (limit taken inside the undone block)',
    "  if not private.fabric_store_take_rate_limit('checkout_10m', v_client_hash, c_per_client_10m, interval '10 minutes')\n     or not private.fabric_store_take_rate_limit('checkout_day', v_client_hash, c_per_client_day, interval '1 day') then\n    return jsonb_build_object('status', 'rate_limited');\n  end if;\n\n  begin\n",
    "  begin\n  if not private.fabric_store_take_rate_limit('checkout_10m', v_client_hash, c_per_client_10m, interval '10 minutes')\n     or not private.fabric_store_take_rate_limit('checkout_day', v_client_hash, c_per_client_day, interval '1 day') then\n    return jsonb_build_object('status', 'rate_limited');\n  end if;\n", false],
  [4, 'the hold lasts 45 minutes', "c_hold interval := interval '30 minutes';", "c_hold interval := interval '45 minutes';", false],
  [4, 'the customer link lasts a day', "c_access interval := interval '90 days';", "c_access interval := interval '1 day';", false],
  [4, 'the line name comes from the request',
    "left(coalesce(nullif(btrim(v_listing.name), ''),", "left(coalesce(v_item ->> 'fabric_name', nullif(btrim(v_listing.name), ''),", false],
  [4, 'the stock unit comes from the request',
    'v_order_id, v_line, v_listing.id, v_listing.inventory_item_id, v_listing.inventory_color_id,',
    "v_order_id, v_line, v_listing.id, coalesce((v_item ->> 'inventory_item_id')::uuid, v_listing.inventory_item_id), v_listing.inventory_color_id,", false],
  [4, 'a card without stock behind it is accepted',
    '      if not found or v_listing.inventory_item_id is null then', '      if not found then', false],
  [4, 'order consistency checked only at commit',
    "                    public.fabric_store_order_addresses_consistency immediate;\n", "                    public.fabric_store_order_addresses_consistency deferred;\n", false],
  [4, 'an order with a payment attempt can be replaced',
    "            and attempt.status in ('created', 'initiated', 'authorized', 'paid')",
    "            and attempt.status in ('paid')", false],
  [4, 'a replaced order keeps its hold',
    "          perform private.fabric_store_release_order_reservations(v_old.id, 'استُبدل بطلب أحدث من نفس المتصفح');\n",
    '', false],
  [4, 'the quote ignores holds', "'reserved_cm', coalesce(hold.reserved_cm, 0)", "'reserved_cm', 0", false],
  [4, 'the quote is not rate limited', "'quote', p_client_hash, 60,", "'quote', p_client_hash, 6000,", false],
  [4, 'the quote takes any number of fabrics', 'cardinality(p_fabric_ids) > 40 then', 'cardinality(p_fabric_ids) > 4000 then', false],
  [4, 'encoding self-check removed (stage 4)',
    "  if position(chr(1602) || chr(1605) || chr(1575) || chr(1588) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then",
    '  if false then', false],

  // --- the third review: each missing guard must fail for its own reason ---
  [2, 'a paid order without a hold is not flagged',
    'if v_reservation_count <> v_item_count or v_bad_reservation then',
    'if v_bad_reservation then', false],
  [2, 'payment checks expiry at transaction start',
    'v_checked_at := clock_timestamp();',
    'v_checked_at := now();', true],
  [2, 'direct release re-locks the order after its hold',
    '    where o.id = new.order_id;\n    if v_order_payment',
    '    where o.id = new.order_id\n    for update;\n    if v_order_payment', true],
  // --- the reviewer's findings (revision 3): each fix must be caught if undone ---
  [3, 'the card in the line need not belong to this stock',
    '      if not v_listing_matches then',
    '      if false then', false],
  [2, 'a payment landing on a dead hold is not flagged',
    "    if new.payment_status = 'paid' and old.payment_status is distinct from 'paid' then",
    '    if false then', false],
  [2, 'the two-hour window is not on the row',
    '  constraint fabric_store_stock_reservations_window\n    check (expires_at <= created_at + interval \'2 hours\')',
    '  constraint fabric_store_stock_reservations_window\n    check (expires_at <= created_at + interval \'100 years\')', false],
  [2, 'an active hold may be extended by hand',
    '  if new.expires_at is distinct from old.expires_at then',
    '  if false then', false],

  // --- the reviewer's findings (revision 2): each fix must be caught if undone ---
  [2, 'audit sequence left with its default grants',
    "  execute format('revoke all on sequence %s from public, anon, authenticated, service_role', v_sequence);",
    '  null;', false],
  [2, 'fulfillment re-check only on the first step',
    "    if new.fulfillment_status in ('preparing', 'ready_for_pickup', 'shipped', 'delivered') then",
    "    if old.fulfillment_status = 'unfulfilled' and new.fulfillment_status = 'preparing' then", false],
  [2, "a paid order's hold may be released by hand",
    "  if new.status = 'released' and old.status = 'active' then",
    '  if false then', false],
  [3, 'anyone signed in may read the holds',
    "  if v_caller = 'anon'\n     or (v_caller = 'authenticated' and not private.can_manage_fabric_operations()) then",
    '  if false then', false],
  [3, "a paid order's hold is released anyway",
    "  if v_payment_status in ('paid', 'partially_refunded', 'refunded') then",
    '  if false then', false],
  [3, 'a price change since the quote is honoured anyway',
    "      if coalesce(round(v_listing_price * 100), -1)::bigint is distinct from v_line.price_per_meter_halalas",
    '      if false', false],
  [3, 'a hidden or deleted fabric is still sold',
    '      if not v_listing_visible then',
    '      if false then', false],
  [3, 'held stock can be deleted from the inventory screen',
    '  before delete on public.fabric_inventory_colors\n  for each row execute function private.fabric_store_block_reserved_stock_delete();',
    '  before delete on public.fabric_inventory_colors\n  for each row when (false) execute function private.fabric_store_block_reserved_stock_delete();', false],
  [3, 'shop guard ignores holds',
    "    if new.quantity > v_free then\n      raise exception using\n        errcode = 'P0001',\n        message = format(\n          'FABRIC_STOCK_RESERVED",
    "    if false then\n      raise exception using\n        errcode = 'P0001',\n        message = format(\n          'FABRIC_STOCK_RESERVED", false],
  [3, 'holds never expire',
    "      where r.inventory_color_id = p_color_id\n        and r.status = 'active'\n        and r.expires_at > now();",
    "      where r.inventory_color_id = p_color_id\n        and r.status = 'active';", false],
  [3, 'released holds still count',
    "      where r.inventory_color_id = p_color_id\n        and r.status = 'active'",
    "      where r.inventory_color_id = p_color_id\n        and r.status in ('active', 'released')", false],
  [3, 'holds on a fabric without colours ignored',
    "      where r.inventory_item_id = p_inventory_item_id\n        and r.inventory_color_id is null\n        and r.status = 'active'",
    "      where r.inventory_item_id = p_inventory_item_id\n        and r.inventory_color_id is null\n        and r.status = 'nothing'", false],
  [3, 'web hold ignores other holds',
    'if v_unit.required_cm > v_physical_cm - v_reserved_cm then', 'if v_unit.required_cm > v_physical_cm then', false],
  [3, 'web hold ignores metre→piece change',
    "         or (v_line.purchase_mode = 'meter' and v_physical_cm in (300, 350)) then", '         or false then', false],
  [3, 'web hold ignores a changed piece length',
    "      if (v_line.purchase_mode = 'piece' and v_line.piece_length_cm is distinct from v_physical_cm)", '      if false', false],
  [3, 'staff cannot read holds',
    'grant execute on function private.fabric_store_stock_hold(uuid, uuid) to authenticated, service_role;',
    'grant execute on function private.fabric_store_stock_hold(uuid, uuid) to service_role;', false],
  [3, 'sweep expires live holds',
    "    where r.status = 'active'\n      and r.expires_at <= now()", "    where r.status = 'active'", false],
  [3, 'hold window uncapped', "p_expires_at > now() + interval '2 hours'", 'false', false],
  [3, 'encoding self-check removed',
    "  if position(chr(1605) || chr(1581) || chr(1580) || chr(1608) || chr(1586) || chr(1577) in v_body) = 0\n     or position(chr(1575) || chr(1604) || chr(1603) || chr(1605) || chr(1610) || chr(1577) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then",
    '  if false then', false],
  [3, 'web hold takes no row lock',
    '      where color.id = v_unit.inventory_color_id\n        and color.inventory_item_id = v_unit.inventory_item_id\n      for update of color;',
    '      where color.id = v_unit.inventory_color_id\n        and color.inventory_item_id = v_unit.inventory_item_id;', true],
  [3, 'shop guard reads holds before taking the row lock',
    '  if new.color_id is not null then\n    select\n      color.current_quantity,',
    '  select hold.reserved_cm, hold.hold_until\n  into v_reserved_cm, v_hold_until\n  from private.fabric_store_stock_hold(new.inventory_item_id, new.color_id) hold;\n  perform pg_sleep(0.3);\n\n  if new.color_id is not null then\n    select\n      color.current_quantity,',
    true,
    ['  select hold.reserved_cm, hold.hold_until\n  into v_reserved_cm, v_hold_until\n  from private.fabric_store_stock_hold(new.inventory_item_id, new.color_id) hold;\n\n  if v_reserved_cm > 0 then',
     '  if v_reserved_cm > 0 then']],
  [3, 'web hold waits forever (no lock_timeout)', "set lock_timeout = '800ms'\nas $$", 'as $$', true],
  [2, 'encoding self-check removed (stage 2)',
    "  if position(chr(1575) || chr(1604) || chr(1591) || chr(1604) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then",
    '  if false then', false],
  [2, 'refund cap removed', 'if v_already + new.amount_halalas > v_attempt_amount then', 'if false then', true],
  [2, 'two open attempts allowed', 'create unique index fabric_store_payment_attempts_one_open_per_order', 'create index fabric_store_payment_attempts_one_open_per_order', true],
  [2, "browser roles keep default privileges",
    "revoke all on table public.fabric_store_orders from public, anon, authenticated, service_role;",
    "revoke all on table public.fabric_store_orders from service_role;", false],
  [2, "RLS off on refunds",
    "alter table public.fabric_store_refunds enable row level security;",
    "", false],
  [2, "service_role may rewrite snapshots",
    "grant select, insert on table public.fabric_store_order_items to service_role;",
    "grant select, insert, update, delete on table public.fabric_store_order_items to service_role;", false],
  [2, "sequence usable by anon",
    "revoke all on sequence public.fabric_store_order_number_seq from public, anon, authenticated, service_role;",
    "revoke all on sequence public.fabric_store_order_number_seq from service_role;", false],
  [2, "VAT truncated",
    "vat_basis_points + 5000) / 10000)",
    "vat_basis_points + 0) / 10000)", false],
  [2, "piece rounded twice",
    "(price_per_meter_halalas * (10000 - discount_basis_points) * piece_length_cm + 500000) / 1000000",
    "((price_per_meter_halalas * (10000 - discount_basis_points) + 5000) / 10000) * piece_length_cm / 100", false],
  [2, "meter line rounded down",
    "(unit_price_halalas * quantity_cm + 50) / 100",
    "(unit_price_halalas * quantity_cm) / 100", false],
  [2, "paid -> failed allowed",
    "or (old.payment_status = 'failed' and new.payment_status = 'paid')",
    "or (old.payment_status = 'failed' and new.payment_status = 'paid') or (old.payment_status = 'paid' and new.payment_status = 'failed')", false],
  [2, "staff changes payment",
    "if v_actor not in ('provider', 'system') then",
    "if v_actor not in ('provider', 'system', 'staff') then", false],
  [2, "actor optional",
    "and (v_actor is null or v_actor not in ('customer', 'staff', 'provider', 'system')) then",
    "and false then", false],
  [2, "prepare unpaid",
    "if new.payment_status not in ('paid', 'partially_refunded') then",
    "if false then", false],
  [2, "prepare under review",
    "      if new.needs_review then",
    "      if false then", false],
  [2, "paid attempt unverified",
    "if v_attempt_order is distinct from new.id or v_attempt_status is distinct from 'paid' then",
    "if false then", false],
  [2, "attempt amount unchecked",
    "if new.amount_halalas is distinct from v_total then",
    "if false then", false],
  [2, "items total unchecked",
    "if v_items_net <> v_order.items_net_halalas then",
    "if false then", false],
  [2, "snapshot trigger removed",
    "create trigger fabric_store_order_items_forbid_update\n  before update on public.fabric_store_order_items\n  for each row execute function private.fabric_store_forbid_update();",
    "", false],
  [2, "audit trigger removed",
    "create trigger fabric_store_orders_log_event\n  after insert or update on public.fabric_store_orders\n  for each row execute function private.fabric_store_log_order_event();",
    "", false],
  [2, "event payload mutable",
    "or new.payload is distinct from old.payload",
    "", false],
  [2, "reservation qty unmatched",
    "or v_item_consumption is distinct from new.quantity_cm then",
    "then", false],
  [2, "expired hold re-activates",
    "or (old.status in ('released', 'expired') and new.status = 'consumed')",
    "or (old.status in ('released', 'expired') and new.status in ('consumed', 'active'))", false],
  [2, "address wiped while open",
    "if not (v_fulfillment_status in ('delivered', 'cancelled') or v_payment_status = 'failed') then",
    "if false then", false],
  [2, "anonymised address editable",
    "if old.anonymized_at is not null then",
    "if false then", false],
  [2, "pickup stores address",
    "if v_delivery_method is distinct from 'shipping' then",
    "if false then", false],
  [2, "shipping without address",
    "if v_order.delivery_method = 'shipping' and not v_has_address then",
    "if false then", false],
  [2, "outbox dedupe removed",
    "constraint fabric_store_outbox_dedupe_key_key unique (dedupe_key),",
    "", false],
  [2, "duplicate events",
    "constraint fabric_store_payment_events_provider_event_key\n    unique (provider, environment, provider_event_id),",
    "", false],
  [2, "totals mutable",
    "or new.total_halalas is distinct from old.total_halalas",
    "", false],
  [2, "orders with attempts deletable",
    "order_id uuid not null references public.fabric_store_orders(id) on delete restrict,\n  provider text not null,",
    "order_id uuid not null references public.fabric_store_orders(id) on delete cascade,\n  provider text not null,", false],
  [2, "audit not writable by server",
    "grant select, insert on table public.fabric_store_order_events to service_role;",
    "grant select on table public.fabric_store_order_events to service_role;", false],
  [2, "provider payment id rewritable",
    "or (old.provider_payment_id is not null and new.provider_payment_id is distinct from old.provider_payment_id) then",
    "then", false],
  [2, "customer touches review flag",
    "if new.needs_review is distinct from old.needs_review and v_actor = 'customer' then",
    "if false then", false],
]

// --- stage 5: payments (SQL entry points + the TypeScript payment logic) ---
const STAGE5_MUTANTS = [
  [5, 'browsers may start payments',
    'revoke all on function public.fabric_store_begin_payment(bytea, text, bytea) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_begin_payment(bytea, text, bytea) from public;', false],
  [5, 'browsers may apply payments',
    'revoke all on function public.fabric_store_apply_payment(uuid, text, jsonb, uuid) from public, anon, authenticated;',
    'revoke all on function public.fabric_store_apply_payment(uuid, text, jsonb, uuid) from public;', false],
  [5, 'apply runs with the caller search_path', "security definer\nset search_path = ''\nset lock_timeout = '2s'",
    "security definer\nset lock_timeout = '2s'", false],
  [5, 'pressing pay again opens a second invoice',
    "    if v_open.status in ('initiated', 'authorized') and v_open.expires_at > clock_timestamp()",
    '    if false and v_open.expires_at > clock_timestamp()', false],
  [5, 'a start in flight is not waited for',
    "    if v_open.status = 'created' and v_open.created_at > clock_timestamp() - interval '2 minutes' then",
    '    if false then', false],
  [5, 'the payment page outlives the hold', 'v_hold_until - c_hold_margin', "v_hold_until + interval '1 hour'", false],
  [5, 'no minimum payment window', 'v_expires < clock_timestamp() + c_min_window', 'v_expires < clock_timestamp()', false],
  [5, 'unlimited attempts per order', 'c_max_attempts integer := 5;', 'c_max_attempts integer := 50;', false],
  [5, 'payment starts not rate limited', "'payment_start', p_client_hash, 10,", "'payment_start', p_client_hash, 1000,", false],
  [5, 'status checks not rate limited', "'payment_status', p_client_hash, 120,", "'payment_status', p_client_hash, 12000,", false],
  [5, 'an http checkout url is attached', "or p_checkout_url is null or p_checkout_url !~ '^https://'", 'or p_checkout_url is null', false],
  [5, 'amount not compared', '       or v_amount is distinct from v_attempt.amount_halalas\n', '', false],
  [5, 'currency not compared', '       or v_currency <> v_attempt.currency\n', '', false],
  [5, 'a hint re-points an attempt with its own invoice',
    'where a.id = p_attempt_hint and a.provider_invoice_id is null;', 'where a.id = p_attempt_hint;', false],
  [5, 'authorisation counted as payment',
    "    elsif v_status in ('paid', 'captured') then", "    elsif v_status in ('paid', 'captured', 'authorized') then", false],
  [5, 'a late failure overwrites any attempt',
    "      if v_attempt.status in ('created', 'initiated', 'authorized') then", '      if true then', false],
  [5, 'a paid order queues no confirmation',
    "          insert into public.fabric_store_outbox (topic, dedupe_key, order_id, payload)\n          values ('confirm_order',",
    "          insert into public.fabric_store_outbox (topic, dedupe_key, order_id, payload)\n          values ('notify_customer',", false],
  [5, 'an overpayment is not flagged', "      if v_result = 'overpaid' then", '      if false then', false],
  [5, 'money on a cancelled order is not flagged', "          if v_order.fulfillment_status = 'cancelled' then", '          if false then', false],
  [5, 'a refund made outside the system is not flagged',
    "    elsif v_status in ('refunded', 'voided') and v_attempt.status = 'paid' then", '    elsif false then', false],
  [5, 'a repeated event is stored twice', '  on conflict (provider, environment, provider_event_id) do nothing\n', '', false],
  [5, 'failed events are retried forever', 'processing_attempts + 1 >= 10', 'processing_attempts + 1 >= 1000', false],
  [5, 'quarantined events are retried',
    "    where e.processing_status in ('received', 'failed')", "    where e.processing_status in ('received', 'failed', 'quarantined')", false],
  [5, 'fresh events are retried while their request still runs',
    "      and e.received_at < now() - interval '1 minute'\n", '', false],
  [5, 'a token sees another order’s attempt',
    'where a.id = p_attempt_id and a.order_id = v_order.id\n  for update;', 'where a.id = p_attempt_id\n  for update;', false],
  [5, 'every refresh asks Moyasar',
    "or v_attempt.last_verified_at < now() - interval '10 seconds')", 'or true)', false],
  [5, 'encoding self-check removed (stage 5)',
    "  if position(chr(1575) || chr(1604) || chr(1591) || chr(1604) || chr(1576) in v_body) = 0\n     or position(chr(1591) || chr(167) in v_body) > 0 then\n    raise exception 'FABRIC_STORE_ENCODING",
    "  if false then\n    raise exception 'FABRIC_STORE_ENCODING", false],

  ['ts:payments.ts', 'the webhook secret is not checked',
    'if (!webhookSecretMatches(event.secret_token, config.webhookSecret)) {', 'if (false) {'],
  ['ts:payments.ts', 'the webhook body is trusted instead of re-fetched',
    'return ok(await processEvent(deps, recorded.event_id, paymentId))',
    'return ok((await applyVerifiedPayment(deps, recorded.event_id, event.data as never)).status)'],
  ['ts:payments.ts', 'card data is stored with the event',
    'created_at: event.created_at ?? null, data: redactPayment(data) }', 'created_at: event.created_at ?? null, data }'],
  ['ts:payments.ts', 'any checkout URL is accepted',
    'if (!isMoyasarCheckoutUrl(invoice.url) || invoice.amount', 'if (invoice.amount'],
  ['ts:payments.ts', 'the invoice amount is not checked',
    'invoice.amount !== begin.amount_halalas || ', ''],
  ['ts:payments.ts', 'a failed creation leaves the attempt open',
    "    await abandon(kind === 'rejected' ? 'create_rejected' : 'create_unknown', (error as Error).message)\n", ''],
  ['ts:payments.ts', 'an event from the other environment is processed',
    '  if (environment !== config.environment) {', '  if (false) {'],
  ['ts:payments.ts', 'no metadata recovery after a crash',
    "if (outcome.status === 'unknown' && payment.invoice_id) {", 'if (false) {'],
  ['ts:payments.ts', 'a transient Moyasar failure quarantines the event',
    "const final = error instanceof MoyasarError && (error.kind === 'not_found' || error.kind === 'rejected')",
    'const final = true'],
  ['ts:payments.ts', 'the return page never asks Moyasar',
    "if (view.status !== 'ok' || !view.verify_due", "if (true || !view.verify_due"],
  ['ts:moyasar.ts', 'live keys work without the launch flag',
    "if (environment === 'live' && (env.FABRIC_STORE_ALLOW_LIVE_PAYMENTS", "if (false && (env.FABRIC_STORE_ALLOW_LIVE_PAYMENTS"],
  ['ts:moyasar.ts', 'a foreign API base is accepted',
    "if (!local || env.NODE_ENV === 'production' || environment === 'live') {", 'if (false) {'],
  ['ts:moyasar.ts', 'Moyasar requests never time out',
    'const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS)', 'const timer = setTimeout(() => {}, REQUEST_TIMEOUT_MS)'],
  ['ts:moyasar.ts', 'the webhook secret comparison always matches',
    '  return timingSafeEqual(a, b)', '  return a.length === b.length'],
]

//   node scripts/db-local/mutate.cjs [2|3|4|5|ts] [name substring]
// Stage 5 SQL mutants run verify-stages.cjs; 'ts:<file>' mutants break a COPY of
// src/lib/server/fabric-store/<file> and run verify-payments.cjs (end to end with the mock).
const only = process.argv[2] || null
const nameFilter = process.argv[3] || null
let total = 0
let caught = 0
for (const [stage, name, find, replace, concurrency, extra] of [...MUTANTS, ...STAGE5_MUTANTS]) {
  if (only && !String(stage).startsWith(only)) continue
  if (nameFilter && !name.includes(nameFilter)) continue
  total += 1
  let args
  if (String(stage).startsWith('ts:')) {
    args = [path.join(__dirname, 'verify-payments.cjs'), '--mutate-ts', String(stage).slice(3), find, replace]
  } else {
    const flag = `--mutate${stage}`
    args = [path.join(__dirname, 'verify-stages.cjs'), flag, find, replace]
    if (extra) args.push(flag, extra[0], extra[1])
    if (!concurrency) args.push('--no-concurrency')
  }
  const run = spawnSync(process.execPath, args, { encoding: 'utf8', timeout: 600000, env: process.env })
  const out = `${run.stdout || ''}${run.stderr || ''}`
  if (run.status === 3) { console.log(`PATTERN MISSING: [${stage}] ${name}`); continue }
  if (run.status === 0) { console.log(`SURVIVED (bad): [${stage}] ${name}`); continue }
  caught += 1
  console.log(`caught: [${stage}] ${name} → ${(out.match(/✘[^\n]*/) || ['(no ✘ line)'])[0].slice(0, 140)}`)
}
console.log(`mutants: ${total}, caught: ${caught}`)
process.exit(caught === total ? 0 : 1)
